### ISSUE TITLE
Export is broken

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#1]
No clojure code runs when a game is exported from the editor.

**Comment by nasser** [comment]
Reopening because while export technically works, a lot of manual effort is required to get there. We'll call this closed when export is as seamless as exporting a non-Arcadia project. This might depend on conditional compilation or better integrating with Unity's export compile chain.

**Comment by timsgardner** [comment]
Maybe we should break it into more fine-grained issues? Totally smooth automated export to every platform sounds like a big project, especially considering the complications we're expecting for iOS.

**Comment by nasser** [comment]
I meant more to call this closed once the manual DLL dance is taken care of. We should open separate issues for platform exports, though.

**Comment by nasser** [comment]
This should be taken care of, but we need to confirm that it works with the new components architecture

**Comment by selfsame** [comment]
re: https://github.com/arcadia-unity/Arcadia/issues/1#issuecomment-73079901

In the Editor inspector for DLLs you can toggle the supported platforms allowing you to exclude the non build-able parts of Arcadia.  Perhaps this could be automated in compilation via meta:

```clj
(ns ^:editor arcadia.repl)
```

Also wondering why editor namespaces are compiled in the first place, does it speed up the environment load?

**Comment by nasser** [comment]
Confirmed working export on OSX, Windows, Linux and Android. Closing this for the alpha.
