### ISSUE TITLE
Regard Overloaded Operators

### ISSUE THREAD

**Issue by OmerShapira** [arcadia-unity/Arcadia#10]
This code:
``` csharp
Vector3.up * 4
``` 
Just works. Which is why this code:
``` clojure
(* 4 (. Vector3 up))
```
should just work, but there are some issues, because clojure doesn't know of the overloaded operators.

Several hints:
1. We can infer if the type has an overloaded operator by searching in `(:members (clojure/reflect thing))`
2. We can call the operator by requesting it eg `op_Addition` from the runtime object.

I think it's ok to give the overloaded operators different names (like a `v*` for vector multiplication), but we're losing a lot of generality this way. Ideas?

**Comment by nasser** [comment]
Outside of the scope of arcadia. the `arcadia.linear` namespace solves most of these issues.
