### ISSUE TITLE
[ReflectionTypeLoadException] Error appearing in Unity's console whenever the scene is played.

### ISSUE THREAD

**Issue by markfarrell** [arcadia-unity/Arcadia#101]
Hi, 
The following error keeps appearing in the Unity (4.6) console whenever the scene is played, and I believe when I click on objects in the scene thereafter. I cannot seem to diagnose the issue, and it doesn't seem to have any affects on the functionality of my software. Is this caused by Arcadia (develop branch)?

![Screenshot of error](http://i.imgur.com/ZPB6m93.png)

**Comment by nasser** [comment]
We're seeing this too. It does not seem to have an impact on the functionality of Arcadia, but we're looking into it.

**Comment by timsgardner** [comment]
Haven't seen this in a while
