### ISSUE TITLE
[TypeNotFoundException] Sometimes unable to find a type. 

### ISSUE THREAD

**Issue by markfarrell** [arcadia-unity/Arcadia#102]
Hi,

I've also encountered an issue where I 'randomly' start getting <code>TypeNotFoundException</code>s. I have a script that uses <code>System.Web.HttpUtility</code>, and this is what happens to me from time to time while I'm working on my project: 

![TypeNotFoundException Screenshot](http://i.imgur.com/6U5Hjw4.png)

Restarting Unity seems to remedy the issue, until it happens again. Anyone else have this issue?

**Comment by nasser** [comment]
Interesting. I haven't seen that before. Can you share the Clojure code that triggers it?

**Comment by markfarrell** [comment]
Just having this function defined in a script triggers it:

```clojure 

(defn url-encode
         "Encodes a URL string."
         [str]
         (System.Web.HttpUtility/UrlEncode str))
```

**Comment by nasser** [comment]
Hmm. Does your ns form `import` it? e.g.

```clojure
(ns foo.bar
  (:use arcadia.core)
  (:import [System.Web HttpUtility]))
```

**Comment by markfarrell** [comment]
It used to, but even then I had similar problems:

![Screenshot](http://i.imgur.com/3TPW5SX.png)

**Comment by nasser** [comment]
Hmm. Is this consistent? Or random like the first error you're getting?

This looks like a bug in ClojureCLR, then. Type resolution has been sticky since the start, because it's considerably different from the JVM (so a straight port is not an option), and we've had to put in optimizations to make it perform. We'll look into it.

**Comment by markfarrell** [comment]
Been fairly consistent.

**Comment by nasser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reproduce issue #102](https://trello.com/c/YaY7Y96Q/16-reproduce-issue-102)

**Comment by nasser** [comment]
Can't reproduce on `beta` branch, Unity 2018.1.0b13 Arch Linux.

```
user=> (defn url-encode
      "Encodes a URL string."
      [str]
      (System.Web.HttpUtility/UrlEncode str))
#'user/url-encode
user=> (url-encode "foo bar baz")
"foo+bar+baz"
user=> (import System.Web.HttpUtility)
System.Web.HttpUtility
user=> (defn url-encode
      "Encodes a URL string."
      [str]
      (HttpUtility/UrlEncode str))
#'user/url-encode
user=> (url-encode "foo bar baz")
"foo+bar+baz"
```

Most likely got fixed along the way.
