### ISSUE TITLE
better introspection faciliites

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#106]
We need some standardized, robust, reliable, well-tested, complete introspection facilities, including pprinting of introspection results, that don't require googling the vagaries of System.Reflection.PropertyInfo and System.Reflection.BindingFlags all the time. Arcadia is very heavy on interop and live coding, and we should streamline the process of inspecting types as much as possible. clojure.reflection is incomplete at the moment and difficult to navigate, overly conservative in the conveniences it exposes. Existing arcadia.reflection namespace needs a lot of work and enhancement, quite possibly should just be arcadia.introspection. I'm inclined to err on the side of lots of convenient functions rather than API minimalism for this particular area of functionality, we need support for strong live coding.

**Comment by nasser** [comment]
Agreed on all points. Is there an existing Clojure library that could serve as a model?

**Comment by nasser** [comment]
`arcadia.introspection` is part of the public API and addresses this
