### ISSUE TITLE
repl problems with unbalanced parenthetical forms

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#107]
`(println ";(")` hangs the repl, in Emacs at least.

**Comment by mpereira** [comment]
Doesn't seem to happen in neither [Vim](https://github.com/arcadia-unity/Arcadia/wiki/Editor%20support#vim) nor the terminal REPL.

**Comment by nasser** [comment]
@mpereira interesting. I see it in Sublime Text. It's a bug in the way we [determine if a form is balanced or not](https://github.com/arcadia-unity/Arcadia/blob/master/Editor/repl-client.rb#L18) before sending it off. We should remove all string literals before doing the checks.

**Comment by selfsame** [comment]
also comments (https://github.com/arcadia-unity/Arcadia/issues/107)

**Comment by nasser** [comment]
Fixed in the upcoming C# repl client

**Comment by nasser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [REPL Rearchitecture](https://trello.com/c/M1b73QrP/1-repl-rearchitecture)

**Comment by nasser** [comment]
The legacy UDP REPL that experienced this issue has been removed from the `beta` branch and replaced with the Socket REPL and nREPL, neither of which exhibit this behavior.
