### ISSUE TITLE
upgrade to include new transducer arities

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#110]
map-indexed is a very useful transducer, for example

**Comment by nasser** [comment]
Are these part of 1.7? Would an update of the ClojureCLR we ship do it?

**Comment by timsgardner** [comment]
Yah

**Comment by timsgardner** [comment]
I think, need to check whether they've percolated into ClojureCLR yet. We can help with that if not.

**Comment by timsgardner** [comment]
I think all the sequence functions have already been upgraded to transducers just  in the course of things
