### ISSUE TITLE
Protocols broken in some cases

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#111]
A `deftype` implementing a protocol found in the same assembly will render the assembly unloadable. 

```clojure
(ns cannotadd)

(defprotocol ITestProtocol
  (test-method [a]))

(deftype TestType []
  ITestProtocol
  (test-method [a] a))
```

This will successfully compile and emit a `cannotadd.clj.dll` assembly, but Mono will refuse to load it complaining that some types could not be loaded. Further inspection with different types and using

```clojure
(.GetType (Assembly/Load "cannotadd.clj") "cannotadd.TestType")
```

shows that only types that implement a protocol defined in the same assembly seem to break.

The reasons are not clear to us. It seems to have something to do with the stub class generated for `TestType`. Removing it solves the problem, but type hinting suffers.

**Comment by timsgardner** [comment]
this is my least favorite so far

**Comment by timsgardner** [comment]
"type hinting suffers" means we resort to runtime reflection for almost everything
