### ISSUE TITLE
ReflectionTypeLoadException with clojure.core.reducers.clj.dll

### ISSUE THREAD

**Issue by sonelliot** [arcadia-unity/Arcadia#116]
For some reason this library cannot be loaded. Since it does not appear to be used by anything, I have temporarily disabled its compilation by commenting out the ``ns``` form at the top of the file.

**Comment by nasser** [comment]
This is an incarnation of #111. It will require a serious compiler patch to resolve, and we're in talks with David Miller about it. Temporarily disabling it/ignoring the error is the best we can to at the moment.

**Comment by sonelliot** [comment]
Ah, I think that @timsgardner mentioned in the mail list that you can workaround this by moving the protocol definition into a separate file. How do you go about debugging these *Unity mono won't load my compiled DLL* issues anyway? I saw the ```ReflectionTypeLoadException``` and couldn't get much useful info out of the stack trace or other variables.
