### ISSUE TITLE
Must check-in compiled clojure components to avoid breaking links to scene

### ISSUE THREAD

**Issue by sonelliot** [arcadia-unity/Arcadia#117]
Ran into this problem today when checking out the source for my game on a different computer. All of the attached clojure components were missing from my game objects. This happens because Unity references the UUID of the compiled component DLL and not the script itself. When you import all of your clojure scripts from scratch new UUIDs are generated for each DLL and the link to the scene is lost.

My workaround at the moment is to just check in the compiled DLLs and meta files. It seems that if there is an existing .meta file for the DLL then Unity will re-use that UUID when the DLL changes.

C# scripts have their UUIDs reference directly. It would be nice to have this for Clojure scripts as well, but I'm not sure how possible that is.

**Comment by nasser** [comment]
Excellent breakdown of the problem. You're totally right. Unity isn't actually aware of Clojure or Arcadia at all. There's a whole internal compiler mechanism that we don't actually hook into. Instead, we just emit DLL files which Unity supports and can load. This means that compiled Clojure files are treated like arbitrary DLLs, and the connection to the original script is not maintained.

Deeper integration seems to run into special-case code and hard coded behavior. We may be able to hook into it in the future (there's a whole internal compiler mechanism we've seen in disassembles that we don't touch) but right now there's not clear path to victory here.

Relevant links

http://forum.unity3d.com/threads/text-based-asset-fileid-guid.203629/#post-1627827
http://forum.unity3d.com/threads/yaml-fileid-hash-function-for-dll-scripts.252075/#post-1695479

**Comment by sonelliot** [comment]
Would one possible solution be to get Arcadia to generate the UUIDs for the compiled DLL files? Since the scripts aren't referenced anywhere in the scene, we could generate the MD4 hash from the script namespace, similar to how it is done for the C# scripts and blat over whatever random UUID Unity generates for the DLL by default. This way, links would only break if you change the namespace of the clojure script file.

**Comment by nasser** [comment]
Interesting. I wonder how Unity would react to our manually overwriting its metadata. This is worth trying for sure.

**Comment by nasser** [comment]
Closing as we no longer emit compiled components ourselves, and `hooks` serialize correctly
