### ISSUE TITLE
Difficult to prevent component from compiling

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#118]
`if-ia` is insufficient

this contributes to GetComponent symbol lookup failures.

**Comment by timsgardner** [comment]
So it seems ia (yeah you're right we need to change that name, in-aot I think would be better) is enough to prevent mutation of the scene graph from top-level side-effecting expressions such as most def forms, but does not block type emission.
I suppose this makes sense. An anonymous function form deep within some branch of a function also emits a type, and you don't want to emit a new type every time you hit that branch; so you need to figure out all your type stuff ahead of time without regard for control flow constructs. 
I bet you could still disable type defining forms with a macro the expansion of which contains no type def anywhere (even down some branch), as I believe ```comment``` does, something like (untested):

```clojure
```

**Comment by timsgardner** [comment]
But in any case we still want to be able to redefine types without cavitating the scene graph, right? Shouldn't that just get swept up by the usual Unity component-redefinition-relinking machinery? If we can't figure out a way to support that consistently, all our component types will be set in stone and any modification of them will destroy any saved scenes involving them. 

Or is it that the usual component relinking machinery does work, but sometimes one accidentally reevaluates a component typedef at runtime and gets into a weird state that's difficult to recover from?

Maybe we need a flow chart of all this stuff after all.

**Comment by nasser** [comment]
Fixed by `hooks`, we no longer emit component types
