### ISSUE TITLE
Setting *warn-on-reflection* in the REPL has no effect

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#124]
```clojure
user=> (.GetType (make-array System.Single 2 2))
Reflection warning, NO_SOURCE_PATH:0:0 - reference to field/property GetType can't be resolved (target class is unknown).
System.Array[]

user=> (set! *warn-on-reflection* false)
false

user=> (.GetType (make-array System.Single 2 2))
Reflection warning, NO_SOURCE_PATH:0:0 - reference to field/property GetType can't be resolved (target class is unknown).
System.Array[]

user=> 
```

**Comment by timsgardner** [comment]
1) I believe `*warn-on-reflection*` is only consulted at the beginning of an evaluation, not during. So 
```clojure
(binding [*warn-on-reflection* true]
  (fn [x]
    (.Glorp x)))
```
does NOT raise a warning if evaluated in the repl with `*warn-on-reflection*`already set to `false`. `*warn-on-reflection*` must be set to `true` before that form is evaluated.

2) We aren't carrying `*warn-on-reflection*` around with repl sessions (unlike `*ns*` and `*print-meta*`, maybe stupidly`). Therefore to set it from the repl one should usually use the following somewhat cumbersome form:
```clojure
(alter-var-root #'*warn-on-reflection* (constantly true))
```
