### ISSUE TITLE
REPL Broken in Unity 5

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#125]
Unity 5 changes the behavior of the `EditorApplication.update` delegate such that it is only called when Unity has focus, breaking the REPL. We mentioned it on the [Unity forums](http://forum.unity3d.com/threads/how-to-keep-the-editor-gui-activein-the-background.296693/#post-2020169), but we don't expect it to be changed any time soon.

The [current solution](https://gist.github.com/nasser/7bcfc6c183f885f7bffc) is a native plugin that creates a timer loop on the main thread and calls the correct internal method using the Mono APIs. A separate native plugin will need to be written for each OS. Native plugins are allowed in the free version of Unity starting in Unity 5.

**Comment by nasser** [comment]
We have the solution wrapped up in a branch now: https://github.com/arcadia-unity/arcadia/tree/unity5-repl-fix. Still OSX only.

**Comment by Guthur** [comment]
I have not noticed this as a problem on Windows, even though it can not load the force editor binary.

**Comment by spoltier** [comment]
I definitely notice this (Win 10). You won't get a response until you tab back into Unity.

**Comment by nasser** [comment]
Thanks for the heads up @spoltier. We even see this from time to time on OSX, even with the native level hack. Needs further investigating.

**Comment by timsgardner** [comment]
Has our understanding of this bug evolved? I remember we had some alternate hypotheses about what might be going on we were going to test.

**Comment by nasser** [comment]
Understanding hasn't evolved much. My next move it to have the native hack invoke our own delegate (instead of Unity's `EditorApplication.update`), but I am not sure that will make much of a difference for this problem.

**Comment by nasser** [comment]
We've removed the native plugin hack and our internal `nudge` namespace seems to solve this for now, as long as the Unity window remains visible. Not a whole lot else we can do.
