### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by Guthur** [arcadia-unity/Arcadia#135]
initialization.cs calls 
RT.var("arcadia.config", "configured-loadpath").invoke()

But configured-loadpath is not defined in arcadia.config.

**Comment by timsgardner** [comment]
What commit? I don't believe there's such a reference in Initialization.cs on latest develop, that is, 775acc2

**Comment by timsgardner** [comment]
ah, yes, sorry, just saw it; wrong commit

**Comment by timsgardner** [comment]
Ok looks like we had a dirty merge last night, sorry about that. Try using 775acc2 for now, hunting down the problem presently.
I'm also going to try to push out an "unstable" branch today that should be more reliable than develop, where we keep states of the repo we're relatively confident aren't broken.

**Comment by timsgardner** [comment]
ok, should be fixed as of d5f4b9b

**Comment by Guthur** [comment]
Excellent, cheers.

Yeah I just reverted to the commit I knew was working, but now i will try out the new one.

Thanks again and keep up the good work, this project is really exciting for lispy game dev.
