### ISSUE TITLE
Component property null when component is recompiled during running game.

### ISSUE THREAD

**Issue by Guthur** [arcadia-unity/Arcadia#136]
I assume this happens because the state gets wiped during the recompile and it does not run the Start or Reset function. Would it be more appropriate to reinitialize the component after a recompile? 

```clojure
(defcomponent game-manager [Vector2 state]
  ; use this for initialization
  (Start [this] (set! state object-initial))

  ; update is called once per frame
  (Update
   [this]
   (Debug/Log state)
   (set! state (update-state state))
   (set! (.. this transform position)
         (v3 (.x (:position state))
             (.y (:position state))
             0.0))))
```
Feel free to close this if you think the game developer should be solving this problem.

**Comment by nasser** [comment]
`defcomponent` was removed because it proved impossible to control or make stable. Use `hooks` instead.
