### ISSUE TITLE
Error calling VimShellInteractive from Vim ("Undefined variable: fdlist")

### ISSUE THREAD

**Issue by gfixler** [arcadia-unity/Arcadia#137]
I'm trying to get the REPL working in Vim, using the instructions found [here](https://github.com/arcadia-unity/arcadia/wiki/Editor-support#vim). I have vimpshell and vimproc working in Vim, but when I run this line in Vim:

```
:VimShellInteractive ruby Assets/Arcadia/Editor/repl-client.rb
```

I get this error:

```
function <SNR>87_vimshell_interactive..vimshell#helpers#execute_internal_command..299..vimproc#ptyopen..<SNR>140_plineopen..<SNR>140_vp_pipe_open..<SNR>140_libcall, line 4
Vim(let):E364: Library call failed for "vp_pipe_open()"
vimproc: Error occurred in calling s:vp_pipe_open()
a:argv = ['C:/Ruby21-x64/bin/ruby.exe', 'Assets/Arcadia/Editor/repl-client.rb']
original a:argv = ['C:/Ruby21-x64/bin/ruby.exe', 'Assets/Arcadia/Editor/repl-client.rb']
ruby Assets/Arcadia/Editor/repl-client.rb: Vim(if):E121: Undefined variable: fdlist
```

Thoughts?

**Comment by mpereira** [comment]
Seems to be a vimproc issue: https://github.com/Shougo/vimproc.vim/issues/215. Try updating and rebuilding it.

**Comment by nasser** [comment]
We're moving away from the Ruby REPL client. That should fix things on windows, hopefully.

**Comment by nasser** [comment]
Closing for now, as the Ruby client and UDP REPL are both deprecated. If we end up supporting vim it will be by some other means.
