### ISSUE TITLE
repl-client.rb issue: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by gfixler** [arcadia-unity/Arcadia#138]
I'm getting this on Win 7 64, Unity 4.6.0b20:

    $ ruby repl-client.rb
    repl-client.rb:11:in `recv': An existing connection was forcibly closed by the remote host. - recvfrom(2) (Errno::ECONNRESET)
            from repl-client.rb:11:in `repl_send'
            from repl-client.rb:23:in `<main>'

**Comment by Quasaur** [comment]
I'm getting the same thing on Win10:
Win10 Pro x64 version 10.0.10240
Unity 5.1.2f1
Java 8u51 JDK (build 1.8.0_51-b16) x64
RubyInstaller 2.2.2 x64
Ruby 2.2.2p95 (2015-04-13 revision 50295) [x86-mingw32]

**Comment by nasser** [comment]
We're working on a replacement for `repl-client.rb` written in C# that should hopefully avoid these issues. If you can reproduce with the new client, let us know.
