### ISSUE TITLE
ForceEditorUpdates.bundle source?

### ISSUE THREAD

**Issue by spacepluk** [arcadia-unity/Arcadia#139]
Hi there,
I'm running Arcadia on wine and it seems to be working great after a few windows-related tweaks.  The only thing that doesn't work for me right now is having the editor to update automatically while unity is in the background.  Would you share the plugin's source so I can recompile it for windows?

**Comment by nasser** [comment]
The source is: https://gist.github.com/nasser/7bcfc6c183f885f7bffc

Unfortunately, the plugin uses an OSX specific trick to trigger the update and can’t be trivially ported. I think we will have to resort to non-portable OS-specific code in any case to pull it off, so we just need someone with Windows C/C++ knowledge to do that.

R

On August 5, 2015 at 2:32:29 AM, Oscar Morante (notifications@github.com) wrote:

Hi there,
I'm running Arcadia on wine and it seems to be working great after a few windows-related tweaks. The only thing that doesn't work for me right now is having the editor to update automatically while unity is in the background. Would you share the plugin's source so I can recompile it for windows?

**Comment by spacepluk** [comment]
I see, isn't there any way to call that method from c#?

**Comment by nasser** [comment]
The problem is you need a timer external to Mono/C# to trigger those methods as far as we can tell.

**Comment by spacepluk** [comment]
Cool, I'll play with it tonight and see if I can manage.

Do you have any idea why an external timer is needed?  I don't know a lot about mono/c# but I don't understand why this would be the case.

**Comment by nasser** [comment]
An external timer is needed because Unity controls the main thread in Mono, and we haven't found a way to intervene on that. So, our code sets up an OS level timer on the main thread that invokes the Mono/C# logic we need to update the editor.

**Comment by spacepluk** [comment]
I see, I wanted to take a look at this but life got in the way :/  I hope I'll have time in a couple of weeks.

**Comment by spacepluk** [comment]
I finaly did some experiments, and it seems that just forcing the update from a different thread isn't enough... I made a simple test using pthreads on linux and the editor freezes :(

I think this needs a different implementation for every eventloop unity is using on every platform... On linux it's probably glib I'll give that a try later, but I have no idea what to test on Windows :?

**Comment by nasser** [comment]
Yeah it will have to be a per-event-loop solution. This is only a problem in Edit mode. Play mode works fine with the REPL.
