### ISSUE TITLE
Stack Traces

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#14]
Stack traces coming out of `.clj` files should not show C# machinery.

**Comment by nasser** [comment]
Maybe controllable via config, part of the general effort to "make error messages better"

**Comment by timsgardner** [comment]
stack traces cleaned as of c56d4c7c4b4a05bfb3decca197187145336e9bca

**Comment by timsgardner** [comment]
stack traces cleaned as of c56d4c7c4b4a05bfb3decca197187145336e9bca
