### ISSUE TITLE
Mismatched hydration keywords?

### ISSUE THREAD

**Issue by sdroadie** [arcadia-unity/Arcadia#140]
Some (technically, at least one) hydration keywords seem mismatched. The one I ran into is Mass on rigidbodies. At least in my environment (Unity 5.1 experimental build on Linux), the Mass value is mapped to the keyword :Mass, while in demos, it's mapped to :mass.

**Comment by nasser** [comment]
We're moving Hydrate out of core, and I believe @timsgardner is planning a rewrite, but I will leave this open for his reference
