### ISSUE TITLE
Does arcadia work with Unity 5.2?

### ISSUE THREAD

**Issue by salmazov** [arcadia-unity/Arcadia#141]
I want to use Unity 5.2 with Clojure.

**Comment by nasser** [comment]
We haven't tested it. There's a good chance that it will. Try and setting it up as usual and report any bugs you find!

**Comment by salmazov** [comment]
Okey, what version of Unity do you use in development?

**Comment by nasser** [comment]
5.0.0 right now

**Comment by jeaye** [comment]
This should be closed.

**Comment by nasser** [comment]
Yup, confirmed working on 5.2.3f1
