### ISSUE TITLE
Unity 5.2 Windows bug when adding Clojure Component

### ISSUE THREAD

**Issue by salmazov** [arcadia-unity/Arcadia#142]
I used tutorial and when I add Clojure Component - > error in the status bar of Unity:

Invalid generated unique path "{input path 'Assets/Clojure/Scripts/new-component.clj")

I used unstable branch.

**Comment by salmazov** [comment]
Solved: folder must be named as Assets/Clojure

**Comment by nasser** [comment]
Oh that's a bug. new-component hasn't been updated to the new folder structure.

**Comment by nasser** [comment]
Fixed on develop! Thanks!
