### ISSUE TITLE
Super subtle bug with swap!

### ISSUE THREAD

**Issue by MysteryMachine** [arcadia-unity/Arcadia#144]
I think this one has something to do with how Unity doesn't do multi threading well, but ok. I had Unity crashing for seemingly no reason, with no real helpful errors, or anything, for like two days now. After extensive testing, I've isolated the bug.

To produce it, in a Clojure file, create a component with an atom, and a component with a Start function. That start function should call swap! on the atom. Now, run the game, and through the REPL instantiate a prefab using Resources/Load. Add this component to the prefab. Stop running the game. Modify your Clojure file by adding a space somewhere, and save. Wait for Arcadia to recompile. Run the scene again.

At this point, you should get a bunch of errors, and a crash. Whenever you load up Unity, you should get lots of crashes until you delete the files associated with the Clojure file in Arcadia/Compiled. 

Works fine if you use reset! instead.

Tested on the develop and unstable branches of Arcadia, on the latest version of Unity.

**Comment by MysteryMachine** [comment]
Wait, my description might still be wrong. I'll get back to you once I have a more accurate description of what's going on.

**Comment by nasser** [comment]
Does this happen on the components branch?

**Comment by nasser** [comment]
Closing for now as it appears to be `defcomponent` specific. If you can reproduce this with the new hooks/state stuff let us know!
