### ISSUE TITLE
ArcadiaBehaviour performance

### ISSUE THREAD

**Issue by selfsame** [arcadia-unity/Arcadia#146]
Every arcadia component will trigger a load, here's a gist of `ArcadiaComponents.cs` that uses `clojure.core/require` 
https://gist.github.com/selfsame/0e031ffeb5e4a4fc5986

**Comment by MysteryMachine** [comment]
+1

**Comment by selfsame** [comment]
so `ArcadiaBehaviour OnAfterDeserialize()` fires all over the place. Twice, for example, during `GameObject.Instantiate`

```clj
(time (do (doseq [i (range 1000)]
  (clone! :hook (->v3 0))) 
  true))
;346 msecs

(time (do (doseq [i (range 1000)]
  (clone! :vanilla (->v3 0))) 
  true))
;65 msecs
```

This might be an argument for moving the fn resolution to the components, perhaps as a try/catch when their message fires

**Comment by selfsame** [comment]
another related idea, `ArcadiaState` could delay the edn `read-str` as a getter with an init check

**Comment by selfsame** [comment]
Here's a working example of deserializing ArcadiaState on the initial getter lookup.  

* Editor inspection or `(.state c)` will trigger this once.
* might need to re-`null` the private `_state` on serialization?
* perf boost :)


```ArcadiaState.cs
using UnityEngine;
using System.Collections;
using clojure.lang;

public class ArcadiaState : MonoBehaviour, ISerializationCallbackReceiver
{
  [TextArea(3,10)]
  public string edn;
  private object _state;
  
    public object state {
      get { 
        if (_state == null){
          Debug.Log("read-string " + edn);
          _state = (object)readString.invoke(edn);} 
        return _state;}
        set {
          _state = value;}}

  static IFn prStr;
  static IFn readString;
  
  static ArcadiaState()
  {
    prStr = (IFn)RT.var("clojure.core", "pr-str");
    readString = (IFn)RT.var("clojure.core", "read-string");
  }
  
  public void OnBeforeSerialize()
  {
    edn = (string)prStr.invoke(state);
  }
  
  public void OnAfterDeserialize()
  {
    //try{state = (object)readString.invoke(edn);}
    //catch{state = edn;}
  }
}
```

**Comment by selfsame** [comment]
## ArcadiaBehaviour inspector perf
`ArcadiaBehaviour`s `Awake` method is spammed when inspector UI is interacted with (via `OnAfterDeserialize`), results in very noticable lag for editor interaction.  Caching deserialized value in `get` would fix.

**Comment by nasser** [comment]
c71ec75fd4e07f80abf66f4b6ac1ec4657754994 spot fixes it, but I am working on a more permanent fix that integrates with @timsgardner's filewatcher
