### ISSUE TITLE
Plugins used from several locations: (Export)

### ISSUE THREAD

**Issue by HugoNikanor** [arcadia-unity/Arcadia#151]
When trying to export a game I get the error message

> Plugin 'clojure.pprint.column_writer.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.pprint.column_writer.clj.dll would be copied to <PluginPath>/clojure.pprint.column_writer.clj.dll
 Assets/Arcadia/Compiled/clojure.pprint.column_writer.clj.dll would be copied to <PluginPath>/clojure.pprint.column_writer.clj.dll
Plugin 'arcadia.repl.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/arcadia.repl.clj.dll would be copied to <PluginPath>/arcadia.repl.clj.dll
 Assets/Arcadia/Compiled/arcadia.repl.clj.dll would be copied to <PluginPath>/arcadia.repl.clj.dll
Plugin 'clojure.instant.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.instant.clj.dll would be copied to <PluginPath>/clojure.instant.clj.dll
 Assets/Arcadia/Compiled/clojure.instant.clj.dll would be copied to <PluginPath>/clojure.instant.clj.dll
Plugin 'arcadia.core.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/arcadia.core.clj.dll would be copied to <PluginPath>/arcadia.core.clj.dll
 Assets/Arcadia/Compiled/arcadia.core.clj.dll would be copied to <PluginPath>/arcadia.core.clj.dll
Plugin 'arcadia.internal.seq_utils.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/arcadia.internal.seq_utils.clj.dll would be copied to <PluginPath>/arcadia.internal.seq_utils.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/arcadia.internal.seq_utils.clj.dll would be copied to <PluginPath>/arcadia.internal.seq_utils.clj.dll
Plugin 'clojure.core_proxy.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.core_proxy.clj.dll would be copied to <PluginPath>/clojure.core_proxy.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.core_proxy.clj.dll would be copied to <PluginPath>/clojure.core_proxy.clj.dll
Plugin 'arcadia.internal.map_utils.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/arcadia.internal.map_utils.clj.dll would be copied to <PluginPath>/arcadia.internal.map_utils.clj.dll
 Assets/Arcadia/Compiled/arcadia.internal.map_utils.clj.dll would be copied to <PluginPath>/arcadia.internal.map_utils.clj.dll
Plugin 'arcadia.hydrate.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/arcadia.hydrate.clj.dll would be copied to <PluginPath>/arcadia.hydrate.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/arcadia.hydrate.clj.dll would be copied to <PluginPath>/arcadia.hydrate.clj.dll
Plugin 'clojure.walk.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.walk.clj.dll would be copied to <PluginPath>/clojure.walk.clj.dll
 Assets/Arcadia/Compiled/clojure.walk.clj.dll would be copied to <PluginPath>/clojure.walk.clj.dll
Plugin 'clojure.core.reducers.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.core.reducers.clj.dll would be copied to <PluginPath>/clojure.core.reducers.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.core.reducers.clj.dll would be copied to <PluginPath>/clojure.core.reducers.clj.dll
Plugin 'clojure.uuid.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.uuid.clj.dll would be copied to <PluginPath>/clojure.uuid.clj.dll
 Assets/Arcadia/Compiled/clojure.uuid.clj.dll would be copied to <PluginPath>/clojure.uuid.clj.dll
Plugin 'clojure.test.junit.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.test.junit.clj.dll would be copied to <PluginPath>/clojure.test.junit.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.test.junit.clj.dll would be copied to <PluginPath>/clojure.test.junit.clj.dll
Plugin 'clojure.string.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.string.clj.dll would be copied to <PluginPath>/clojure.string.clj.dll
 Assets/Arcadia/Compiled/clojure.string.clj.dll would be copied to <PluginPath>/clojure.string.clj.dll
Plugin 'arcadia.messages.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/arcadia.messages.clj.dll would be copied to <PluginPath>/arcadia.messages.clj.dll
 Assets/Arcadia/Compiled/arcadia.messages.clj.dll would be copied to <PluginPath>/arcadia.messages.clj.dll
Plugin 'arcadia.internal.zip_utils.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/arcadia.internal.zip_utils.clj.dll would be copied to <PluginPath>/arcadia.internal.zip_utils.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/arcadia.internal.zip_utils.clj.dll would be copied to <PluginPath>/arcadia.internal.zip_utils.clj.dll
Plugin 'clojure.edn.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.edn.clj.dll would be copied to <PluginPath>/clojure.edn.clj.dll
 Assets/Arcadia/Compiled/clojure.edn.clj.dll would be copied to <PluginPath>/clojure.edn.clj.dll
Plugin 'arcadia.internal.meval.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/arcadia.internal.meval.clj.dll would be copied to <PluginPath>/arcadia.internal.meval.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/arcadia.internal.meval.clj.dll would be copied to <PluginPath>/arcadia.internal.meval.clj.dll
Plugin 'arcadia.internal.macro.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/arcadia.internal.macro.clj.dll would be copied to <PluginPath>/arcadia.internal.macro.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/arcadia.internal.macro.clj.dll would be copied to <PluginPath>/arcadia.internal.macro.clj.dll
Plugin 'clojure.pprint.pretty_writer.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.pprint.pretty_writer.clj.dll would be copied to <PluginPath>/clojure.pprint.pretty_writer.clj.dll
 Assets/Arcadia/Compiled/clojure.pprint.pretty_writer.clj.dll would be copied to <PluginPath>/clojure.pprint.pretty_writer.clj.dll
Plugin 'clojure.set.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.set.clj.dll would be copied to <PluginPath>/clojure.set.clj.dll
 Assets/Arcadia/Compiled/clojure.set.clj.dll would be copied to <PluginPath>/clojure.set.clj.dll
Plugin 'arcadia.docs.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/arcadia.docs.clj.dll would be copied to <PluginPath>/arcadia.docs.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/arcadia.docs.clj.dll would be copied to <PluginPath>/arcadia.docs.clj.dll
Plugin 'clojure.pprint.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.pprint.clj.dll would be copied to <PluginPath>/clojure.pprint.clj.dll
 Assets/Arcadia/Compiled/clojure.pprint.clj.dll would be copied to <PluginPath>/clojure.pprint.clj.dll
Plugin 'clojure.reflect.clr.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.reflect.clr.clj.dll would be copied to <PluginPath>/clojure.reflect.clr.clj.dll
 Assets/Arcadia/Compiled/clojure.reflect.clr.clj.dll would be copied to <PluginPath>/clojure.reflect.clr.clj.dll
Plugin 'clojure.pprint.print_table.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.pprint.print_table.clj.dll would be copied to <PluginPath>/clojure.pprint.print_table.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.pprint.print_table.clj.dll would be copied to <PluginPath>/clojure.pprint.print_table.clj.dll
Plugin 'clojure.core_deftype.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.core_deftype.clj.dll would be copied to <PluginPath>/clojure.core_deftype.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.core_deftype.clj.dll would be copied to <PluginPath>/clojure.core_deftype.clj.dll
Plugin 'clojure.data.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.data.clj.dll would be copied to <PluginPath>/clojure.data.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.data.clj.dll would be copied to <PluginPath>/clojure.data.clj.dll
Plugin 'arcadia.introspection.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/arcadia.introspection.clj.dll would be copied to <PluginPath>/arcadia.introspection.clj.dll
 Assets/Arcadia/Compiled/arcadia.introspection.clj.dll would be copied to <PluginPath>/arcadia.introspection.clj.dll
Plugin 'clojure.core_clr.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.core_clr.clj.dll would be copied to <PluginPath>/clojure.core_clr.clj.dll
 Assets/Arcadia/Compiled/clojure.core_clr.clj.dll would be copied to <PluginPath>/clojure.core_clr.clj.dll
Plugin 'clojure.clr.io.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.clr.io.clj.dll would be copied to <PluginPath>/clojure.clr.io.clj.dll
 Assets/Arcadia/Compiled/clojure.clr.io.clj.dll would be copied to <PluginPath>/clojure.clr.io.clj.dll
Plugin 'clojure.core.protocols.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.core.protocols.clj.dll would be copied to <PluginPath>/clojure.core.protocols.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.core.protocols.clj.dll would be copied to <PluginPath>/clojure.core.protocols.clj.dll
Plugin 'clojure.pprint.dispatch.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.pprint.dispatch.clj.dll would be copied to <PluginPath>/clojure.pprint.dispatch.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.pprint.dispatch.clj.dll would be copied to <PluginPath>/clojure.pprint.dispatch.clj.dll
Plugin 'arcadia.literals.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/arcadia.literals.clj.dll would be copied to <PluginPath>/arcadia.literals.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/arcadia.literals.clj.dll would be copied to <PluginPath>/arcadia.literals.clj.dll
Plugin 'clojure.reflect.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.reflect.clj.dll would be copied to <PluginPath>/clojure.reflect.clj.dll
 Assets/Arcadia/Compiled/clojure.reflect.clj.dll would be copied to <PluginPath>/clojure.reflect.clj.dll
Plugin 'clojure.zip.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.zip.clj.dll would be copied to <PluginPath>/clojure.zip.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.zip.clj.dll would be copied to <PluginPath>/clojure.zip.clj.dll
Plugin 'arcadia.linear.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/arcadia.linear.clj.dll would be copied to <PluginPath>/arcadia.linear.clj.dll
 Assets/Arcadia/Compiled/arcadia.linear.clj.dll would be copied to <PluginPath>/arcadia.linear.clj.dll
Plugin 'clojure.template.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.template.clj.dll would be copied to <PluginPath>/clojure.template.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.template.clj.dll would be copied to <PluginPath>/clojure.template.clj.dll
Plugin 'clojure.main.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.main.clj.dll would be copied to <PluginPath>/clojure.main.clj.dll
 Assets/Arcadia/Compiled/clojure.main.clj.dll would be copied to <PluginPath>/clojure.main.clj.dll
Plugin 'clojure.repl.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.repl.clj.dll would be copied to <PluginPath>/clojure.repl.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.repl.clj.dll would be copied to <PluginPath>/clojure.repl.clj.dll
Plugin 'arcadia.updater.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/arcadia.updater.clj.dll would be copied to <PluginPath>/arcadia.updater.clj.dll
 Assets/Arcadia/Compiled/arcadia.updater.clj.dll would be copied to <PluginPath>/arcadia.updater.clj.dll
Plugin 'arcadia.internal.editor_interop.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/arcadia.internal.editor_interop.clj.dll would be copied to <PluginPath>/arcadia.internal.editor_interop.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/arcadia.internal.editor_interop.clj.dll would be copied to <PluginPath>/arcadia.internal.editor_interop.clj.dll
Plugin 'clojure.core.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.core.clj.dll would be copied to <PluginPath>/clojure.core.clj.dll
 Assets/Arcadia/Compiled/clojure.core.clj.dll would be copied to <PluginPath>/clojure.core.clj.dll
Plugin 'clojure.core_print.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.core_print.clj.dll would be copied to <PluginPath>/clojure.core_print.clj.dll
 Assets/Arcadia/Compiled/clojure.core_print.clj.dll would be copied to <PluginPath>/clojure.core_print.clj.dll
Plugin 'clojure.pprint.pprint_base.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.pprint.pprint_base.clj.dll would be copied to <PluginPath>/clojure.pprint.pprint_base.clj.dll
 Assets/Arcadia/Compiled/clojure.pprint.pprint_base.clj.dll would be copied to <PluginPath>/clojure.pprint.pprint_base.clj.dll
Plugin 'clojure.test.tap.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.test.tap.clj.dll would be copied to <PluginPath>/clojure.test.tap.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.test.tap.clj.dll would be copied to <PluginPath>/clojure.test.tap.clj.dll
Plugin 'arcadia.reflect.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/arcadia.reflect.clj.dll would be copied to <PluginPath>/arcadia.reflect.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/arcadia.reflect.clj.dll would be copied to <PluginPath>/arcadia.reflect.clj.dll
Plugin 'clojure.test.clj.dll' is used from several locations:
 Assets/Arcadia/Compiled/clojure.test.clj.dll would be copied to <PluginPath>/clojure.test.clj.dll
 Assets/Arcadia/Infrastructure/Compiled/clojure.test.clj.dll would be copied to <PluginPath>/clojure.test.clj.dll
Plugin 'clojure.pprint.cl_format.clj.dll' is used from several locations:
 Assets/Arcadia/Infrastructure/Compiled/clojure.pprint.cl_format.clj.dll would be copied to <PluginPath>/clojure.pprint.cl_format.clj.dll
 Assets/Arcadia/Compiled/clojure.pprint.cl_format.clj.dll would be copied to <PluginPath>/clojure.pprint.cl_format.clj.dll
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at /home/builduser/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.HostView:OnGUI()

Toggling the files mentioned above to only appear in editor (and not in the exported build) makes the error's go away for that file.

This is on the unstable branch with the latest version of Unity 5.3.5f1 Personal

**Comment by nasser** [comment]
We are still working out the kinks in export. It certainly works, but there is some manual clean up that needs to be done that we are working to eliminate. Can you try and reproduce this on the develop branch?

**Comment by HugoNikanor** [comment]
I'm not currently able to reproduce this on the development branch, due to my code not working on it.

But I must ask, is there any documentation of your "hooks" api, other than the twitter screenshots?

**Comment by nasser** [comment]
No documentation yet, unfortunately. The API isn't final, and we're actively working on it. Reading the source and samples on https://gitter.im/arcadia-unity/Arcadia are your best bet until we have a first release.

**Comment by nasser** [comment]
Our export has stabilized. Closing this for now, but if it still breaks for you let us know.
