### ISSUE TITLE
Vec3 in object state is not persistent.

### ISSUE THREAD

**Issue by djeis97** [arcadia-unity/Arcadia#153]
When unity reloads everything, vec3s (and possibly other data structures) stored in the state map of objects are not loaded correctly, instead being replaced with a PersistentList containing a form which creates a new vec3 with the same contents.

To reproduce from a blank unity project,
```
(use 'arcadia.core 'arcadia.linear)
(def cube (create-primitive :cube))
(set-state! cube :key (v3))
```
Transition to playing in unity and the inspector will stop showing the vec3, errors and warnings will be logged to the console (I believe relating to Unity not knowing how to draw the GUI for a PersistentList) and looking at the state of the object at the repl reveals that the `:key` keyword has been replaced with `(new UnityEngine.Vector3 1.0 1.0 1.0)`.

**Comment by nasser** [comment]
I know where this is coming from. On it.
