### ISSUE TITLE
Stop creating unbound vars from *Hook components 

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#154]
Using `RT.var` in [ArcadiaBehaviour.cs](https://github.com/arcadia-unity/Arcadia/blob/develop/Components/ArcadiaBehaviour.cs#L48) causes hooks to create unbound vars when they can't find their vars.

We could use `Compiler.LookupVar`, which is what `TheVar+Parser` uses to parse the `var` special form.

**Comment by selfsame** [comment]
The scenario for this is
* user removes/refactors a fn from a ns
* ArcadiaBehaviour creates an unbound var during deserialization
* the hook throws an error every for that var every time it fires
* user can't remove that var from the repl (serialized hook fns don't have an index to `hook-`, and there is no inspector UI to remove them)
* user has to remove the entire hook and repopulate it

Solutions could be:
1. remove hook `fns` when the namespace exists but the `var` isn't bound.
2. fix `hook-` to serialize fn indexes or remove by var hash
3. add buttons to the hook inspector for removal

**Comment by nasser** [comment]
Fixed in rewrite of internal hook logic

**Comment by timsgardner** [comment]
5d1ba134e1ac384569348593f79d3a1223826361
