### ISSUE TITLE
On windows:  Editor can't be re-opened after installing Arcadia develop branch

### ISSUE THREAD

**Issue by Mechrophile** [arcadia-unity/Arcadia#155]
reproduce
windows 10, Unity 5.3.5f1
follow normal steps to import arcadia, then close the project and reopen.
- editor launches idling at 0.0% cpu in background
- UDP port 11211 connection **is** made
- editor load will resume if a connection to the repl is made from an external client
- this bug can be prevented by commenting out StartRepl() of the initialize method in Arcadia/Editor/initialization.cs **before** arcadia is imported for the first time

edit: split this issue into two, along with #157 updated description

**Comment by nasser** [comment]
Very odd. Can you attach your [log file](https://docs.unity3d.com/Manual/LogFiles.html)?

**Comment by Mechrophile** [comment]
Okay, first the log up to the crash... I'm looking at it and dont see any errors - possibly because I had to kill the process, which prevented it from successfully appending the crash data to the log?
[Editor-crash.txt](https://github.com/arcadia-unity/Arcadia/files/399462/Editor-crash.txt)

**Comment by Mechrophile** [comment]
Okay, then if I attempt to display the project again, the project select panel disappears, but the project window isnt loaded:
[Project-Wont-Display.txt](https://github.com/arcadia-unity/Arcadia/files/399471/Project-Wont-Display.txt)

**Comment by Mechrophile** [comment]
Then if I try to re-open unity and re-select the project, it throws an error saying i cant open the project twice:
[attempt-to-re-load-project.txt](https://github.com/arcadia-unity/Arcadia/files/399473/attempt-to-re-load-project.txt)

**Comment by Mechrophile** [comment]
At the suggestion of selfsame, I tried removing the Arcadia directory and reloading the project in order to load into the editor.  didnt work  -- it still only loaded into a background process.  here's the log:

[arcadia-removed-still-wont-load-editor.txt](https://github.com/arcadia-unity/Arcadia/files/399588/arcadia-removed-still-wont-load-editor.txt)

**Comment by Mechrophile** [comment]
[unsuccessful-loading-existing-project-without-repl-start.txt](https://github.com/arcadia-unity/Arcadia/files/399617/unsuccessful-loading-existing-project-without-repl-start.txt)

**Comment by Mechrophile** [comment]
now attempting to remove repl initialization from startup.

![image](https://cloud.githubusercontent.com/assets/2494198/17368967/584f4658-5964-11e6-96d4-028d34eac610.png)

success!

[successfully-started-project-when-repl-never-started.txt](https://github.com/arcadia-unity/Arcadia/files/399645/successfully-started-project-when-repl-never-started.txt)

**Comment by Mechrophile** [comment]
just to clarify a few things:

- With no code change, if I stop the REPL before exiting the editor, the editor does not crash.  However, the project will still be loaded in the background only if I try to reopen it -- no editor window is displayed

- the problem (project not loading) was not present if I comment out StartREPL() **before I ever import arcadia**.

- The problem **is present** if I comment out StartREPL() after the Arcadia is imported the first time

**Comment by selfsame** [comment]
via @worrel with procmon

https://www.dropbox.com/s/c7pz46yjpi7pblr/unity-wait-chain-on-freeze.PNG?dl=0

**Comment by nasser** [comment]
Excellent detective work everyone! This confirms that this is a REPL closure issue on Windows. I will revisit our REPL teardown code and push out a fix as soon as I can.

**Comment by selfsame** [comment]
on the contrary this issue is caused by the repl socket being opened in initialization.cs too early which somehow blocks the unity editor from loading in windows 10, issue #157 has similar symptoms and is caused by the socket being closed before the editor quits -  thanks!

**Comment by nasser** [comment]
OK – thanks for the clarification. I will really need a Windows machine to look into this. I have a Windows 7 rig in the lab that I will dual boot to Windows 10 when I get back.

In the meantime, how about replacing `arcadia.repl/start-server` with this:

```clojure
(defn start-server [^long port]
  (if @server-running
    (Debug/Log "REPL already running")
    (Debug/Log "Starting REPL"))
  (when-not @server-running
    (reset! server-running true)
    (let [socket (UdpClient. (IPEndPoint. IPAddress/Any port))]
      (set! (.. socket Client SendBufferSize) (* 1024 5000)) ;; 5Mb
      (set! (.. socket Client ReceiveBufferSize) (* 1024 5000)) ;; 5Mb
      (.Start (Thread. (gen-delegate ThreadStart []
                                     (Thread/Sleep 5000)
                                     (if (@configuration :verbose)
                                       (Debug/Log "Starting REPL..."))
                                     (while @server-running
                                       (listen-and-block socket))
                                     ;; TODO why does this line not execute?
                                     (if (@configuration :verbose)
                                       (Debug/Log "REPL Stopped")))))
      socket)))
```

The `Thread/Sleep` line is the new one. Would that simulate the REPL starting "later", do you think?

**Comment by worrel** [comment]
@nasser that Sleep did the trick! (at 5000 & 1000, though not 100)

**Comment by worrel** [comment]
I should add that attempting to exit Unity after successfully loading an Arcadia project, connecting the REPL & successfully doing a `(create-primitive)` call caused Unity to hang.  I think @Mechrophile mentioned this somewhere (have to stop REPL before quitting)

**Comment by nasser** [comment]
Thanks @worrel! OK, so this is some kind of timing bug with opening the socket "too soon". That kind of stuff makes me nervous. I will look into it as soon as I get the chance. In the meantime, sleep the REPL on startup as above and stop the REPL before quitting Unity to dodge #157. Not great, but at least there are workarounds in place until we get real fixes in.

**Comment by selfsame** [comment]
this bug reproduces in Windows 7 with Unity 5.4.03f (it's not just a windows 10 thing)
