### ISSUE TITLE
Null reference exception when closing REPL that's already been stopped

### ISSUE THREAD

**Issue by Mechrophile** [arcadia-unity/Arcadia#156]
```
(defn start-server [^long port]
  (if @server-running
    (Debug/Log "REPL already running")
    (Debug/Log "Starting REPL"))
  (when-not @server-running
 ...

(defn stop-server [^UdpClient socket]
  (if (@configuration :verbose)
    (Debug/Log "Stopping REPL..."))
  (reset! server-running false)
  (.Close socket))
```

looks like only the start server command checks to see whether or not the server has already been closed.

I get the folllowing error in unity when I try to stop an already stopped repl:

![image](https://cloud.githubusercontent.com/assets/2494198/17408686/38ca9716-5a3a-11e6-8df6-7037a64d2284.png)

Looks like its probably isolated to just throwing that error.

**Comment by timsgardner** [comment]
close as of 47099c6d32c2c3296ae92a3cf89bcbe322888a78

**Comment by Mechrophile** [comment]
yeh broke me:

[no-repl.txt](https://github.com/arcadia-unity/Arcadia/files/463248/no-repl.txt)

**Comment by Mechrophile** [comment]
nevermind, that was caused by pulling new stuff.  just had to restart
