### ISSUE TITLE
I want the ability to reset the complete state of a game object, not just one key at a time

### ISSUE THREAD

**Issue by Mechrophile** [arcadia-unity/Arcadia#161]
Would like to be able to do something like the following:

```
(let [current-state (state my-game-object)]
  (set-state my-game-object (-> current-state
                                (assoc :some-thing new-value)
                                (assoc :some-other-thing other-new-value))))
```

**Comment by timsgardner** [comment]
Will confirm my memory with @nasser, but I think our policy is to not expose this feature, for the following reasons:
- We want to emphasize the mutual independence of keyed bits of state, so stateful systems don't collide with each other's assumptions. This isn't necessary for clj maps, but clj maps are immutable.
- We want to reserve the option of changing our state implementation in a way that this would preclude.

Maybe this could bear rethinking. I'd say that if we did expose a feature like this, it would have to have atom-like semantics to preserve thread safety (Unity's types don't support concurrency, but our stuff tacked onto Unity's types can). In any event a document describing our thinking and policy would be useful.

**Comment by nasser** [comment]
@timsgardner this is my recollection as well. 

We want to encourage libraries, composability, and reuse. The use case we have in mind is that you can construct an object using a number of libraries, and those libraries do not need to know about each other and do not conflict. The problem case setting the whole state leads to is that now a library *can easily remove data another library depends on*. If library A calls `(set-state go {...})` now any data library B, or C had in there is *gone* and only A's view remains. We don't want this.

A case can be made for `merging into` the state, though, which when combined with namespace qualified keys, achieves both the composability we think is important and this use case that is a valid one. @Mechrophile's code becomes

```clojure
(let [current-state (state my-game-object)]
  (merge-state! my-game-object (-> current-state
                                  (assoc ::some-thing new-value)
                                  (assoc ::some-other-thing other-new-value))))
```

**Comment by Mechrophile** [comment]
I definitely understand and support @timsgardner 's merge-state!

**Comment by nasser** [comment]
Closing. Further conversations around the state system are happening at #228.
