### ISSUE TITLE
make `leiningen-project-file?` more robust

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#170]
Must give a negative for the (plausible) cases of having a `project.clj` file at some other level or without a `defproject`

**Comment by nasser** [comment]
So what's the heuristic? A `project.clj` file with no `defcomponent` form?

**Comment by timsgardner** [comment]
defcomponent?

**Comment by timsgardner** [comment]
closed as of 55a0bb3e51572ee938d5ebae32d358108e8a254f

**Comment by nasser** [comment]
i meant `defproject` oops
