### ISSUE TITLE
support .cljc files

### ISSUE THREAD

**Issue by selfsame** [arcadia-unity/Arcadia#171]
in lieu of getting clojureCLR to handle reader conditionals (https://github.com/clojure/clojure-clr/commit/fb7f09137516052271de86d8d5a3b6331bc29f19) Arcadia could at least recognize the `.cljc` mime type.

(Some libs use `.cljc` without any conditionals which allows usage in both jvm clojure and clojurescript )

**Comment by nasser** [comment]
Agreed. We hardcode `clj` in a bunch of places and shouldn't.

**Comment by timsgardner** [comment]
Do we really need this for 0.1? If it's going to be a pain I vote we kick it down the road.

**Comment by selfsame** [comment]
It used to be as simple as changing the regex to ".cljc?$" in these two fns https://github.com/arcadia-unity/Arcadia/blob/develop/Source/arcadia/compiler.clj#L46-L62

**Comment by nasser** [comment]
I think it might be as simple as changing the regexp. Miller already ported reader conditionals to ClojureCLR. It would make a lot of packages more useable, maybe?

**Comment by nasser** [comment]
Should be fixed in 3656c7e09fc145990ad1cc64170ab256c484d6cd, but I'll reopen if this proves to be buggy.
