### ISSUE TITLE
stop vars printing values!

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#172]
representations of vars currently print their values!
```clojure
filewatcher-fixum=> (def bla (range 10))
#<Var@c2eb9900: (0 1 2 3 4 5 6 7 8 9)>
```
This is bad! Values can be or contain lazy data, which will be (fully!) realized by printing!

**Comment by nasser** [comment]
Hmm, I'm not seeing this

```
$ node repl-client.javascript
; Arcadia REPL
; Clojure 1.7.0-master-SNAPSHOT
; Unity 5.2.3f1 (f3d16a1fa2dd)
; Mono 2.6.5 (tarball)
nil

user=> (def bla (range 10))
#'user/bla

user=>
```

**Comment by timsgardner** [comment]
Oops figured it out. `pprint`-ing a var will print out its value for some stupid reason, and I have a thing turned on that pprints all repl output. Turning it off resolves this.

**Comment by nasser** [comment]
hmm ClojureJVM does not do that... maybe something we should look into?

```clojure
user=> (use 'clojure.pprint)
(use 'clojure.pprint)
nil
user=> (def bla (range 10))
(def bla (range 10))
#'user/bla
user=> (pprint (def bla (range 10)))
(pprint (def bla (range 10)))
#'user/bla
nil
user=> 
```

**Comment by timsgardner** [comment]
weerd
