### ISSUE TITLE
Repl.exe cannot be run from outside Infrastructure folder

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#176]
Merge Clojure.dll and AOT'd namespaces into Repl.exe so it no longer depends on where its called in the filesystem.

**Comment by timsgardner** [comment]
that's a bit weird

**Comment by timsgardner** [comment]
you mean so we can take it out of arcadia and call it anywhere? or that we can run it in place but with our cwd anywhere?

**Comment by gdeer81** [comment]
steps to reproduce this:
```
cd ~
bash /path/to/repl
```

I found this issue when I was trying to modify @timsgardner's emacs code to have it hook inf-clojure into the c# repl instead of the node repl. 

```
(defun unity-node-repl ()
  (inf-clojure "bash /path/to/my/project/repl")
  (unity-repl-mode)
  (add-to-list 'comint-preoutput-filter-functions
	       'unity-repl-node-preoutput)
(setq comint-process-echoes 't))

```
since that  executes outside of the Infrastructure folder, it was throwing errors about not being able to find the assembled files it needs.

**Comment by timsgardner** [comment]
and there's no way to correctly set the cwd C#-side?
If merging in some dll's is the easiest way to fix this and doesn't have unintended consequences, let's just do that, though.

**Comment by nasser** [comment]
@gdeer81 just pushed a potential fix to c93912e. Does that work for you?

**Comment by nasser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pass Through Socket REPL](https://trello.com/c/M1b73QrP/1-pass-through-socket-repl)

**Comment by nasser** [comment]
`Repl.exe` was a client for legacy UDP REPL which was removed from the beta branch. Going forward our REPLs are the Socket REPL and nREPL, neither of which need an external client program.
