### ISSUE TITLE
sufficient documentation about top-level scene graph problems

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#183]
Mutating the scene graph from the top level causes huge problems, since we can't control when the static initializer corresponding to top-level forms gets invoked by Unity. Users should therefore save their scene-graph mutations for the Awake or Start methods/hooks of GameObjects created in the repl and saved into the scene graph before export. This is very counterintuitive, and we need better documentation of it.

See #182 for an example of its problems.

**Comment by nasser** [comment]
Specifically, we don't control when Unity loads the scene graph and when it loads Clojure code, and that timing can be different in the editor and in export.

The "bad things" that happen are your code runs before the scene exists, and you are querying a non-existent scene which mostly results in null reference exceptions but I guess is technically undefined?

Maybe this should be a new entry at the bottom of the [Programming in Arcadia](https://github.com/arcadia-unity/Arcadia/wiki/Programming-in-Arcadia) page?
