### ISSUE TITLE
Awake hook does not work

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#187]
We recently moved our deserialization logic to Awake and it is interfering with user code.

**Comment by LispEngineer** [comment]
I'd like to +1 this please. It would be nice for user Awake hooks to work properly, as that is a key part of the Unity game event loop.
https://docs.unity3d.com/Manual/ExecutionOrder.html

**Comment by nasser** [comment]
Yup. This is a pretty serious bug. I will try and get to it first when I squash bugs next.

**Comment by spacepluk** [comment]
[this](https://github.com/spacepluk/Arcadia/commit/bb66c0f18b2ae3f36eeef1eeb002860eefc798a2) seems to be working fine for me.  I can prepare a PR if you like it :)
