### ISSUE TITLE
Request: Arcadia REPL initialization file

### ISSUE THREAD

**Issue by LispEngineer** [arcadia-unity/Arcadia#188]
Given that the REPL constantly needs initialization with common forms like `(require 'arcadia.core)` and such, I suggest that you create an rc/init file in a fixed location such as `Assets/arcadiarc.clj` which contains forms that will (if present) be executed every time the REPL starts up. This way you can put any initialization code you want in there and the REPL will be easier to use. I'd personally use it to require the Arcadia namespaces and my project's namespaces as well as issue an `in-ns` to my my primary core NS.

**Comment by selfsame** [comment]
`Assets/user.clj` will do this exact thing :)

**Comment by timsgardner** [comment]
you can also specify `:injections` in your `configuration.edn`, these are forms that get evaluated every time you send anything to the repl. useful for idempotent stuff that you really want in *every* namespace you're repling into, like `(use clojure.pprint)`, `(use 'clojure.repl)`, etc
