### ISSUE TITLE
Add a link to the homepage

### ISSUE THREAD

**Issue by whilo** [arcadia-unity/Arcadia#191]
I have only found the homepage through @selfsame, maybe you could links to the repo description and README?

**Comment by whilo** [comment]
The group page for arcadia-unity here on github links to http://arcadia-unity.com/, which does not seem to exist.

**Comment by nasser** [comment]
Done. Wow, a lot of that was super old info. We were updating `README.md` on the `master` branch for a while and never moved that stuff over. Thanks!
