### ISSUE TITLE
Adding/removing hooks doesn't mark the scene as dirty

### ISSUE THREAD

**Issue by hatmatter** [arcadia-unity/Arcadia#194]
When you add and remove hooks to a game object via the repl the scene which contains the game object is not marked as dirty. This means that Unity will not offer to Save the scene on Quit and File->Save Scenes does not persist the changes to the game object. Right clicking on the scene in the Hierarchy and explicitly saving it _does_ persist the changes to disk.

It seems like the correct behavior here is for modifying hooks on game objects dirties the scene in which they are contained.

**Comment by nasser** [comment]
The quick solution would be that any REPL interaction marks the scene as dirty. Beyond that we'd have to figure out whether user code mutated the scene graph or not, and that's hard to say.
