### ISSUE TITLE
Ahead of Time compiling user code

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#198]
AOTing Clojure source to `dll` files is a requirement for fast load times. We can AOT `clojure.core` and the `arcadia.*` namespaces, but as the user's codebase gets bigger they will encounter slow load times as well. 

An API to control the AOTing of user code is important to deal with this.

**Comment by timsgardner** [comment]
What do you mean by "an API"? Like a button or a widget? Config options? All of the above?

**Comment by nasser** [comment]
A solution is present on the newly merged `build` branch via the menu
