### ISSUE TITLE
Hooks are not tolerant of exceptions

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#199]
If a var's namespace throws an exception on load, any hooks referencing it will loose that reference.

**Comment by timsgardner** [comment]
Can you provide code that reproduces this?

**Comment by jeaye** [comment]
@timsgardner I've just reproduced this by moving a file into a directory which is not in the load path.

For example, some file `Assets/foo/example.clj`:
```clojure
(ns foo.example
    (:require [arcadia.core :refer :all]))

(defn update! [obj]
  (log "meow"))
```

Let's say I have a hook on some object: `(hook+ obj :update :example #'foo.example/update!)`

If I move the file to another directory, which I forget to add to the load path: `Assets/src/foo/example.clj` and then I restart the game in the editor, the hook on the object will be lost.

**Comment by timsgardner** [comment]
5d1ba134e1ac384569348593f79d3a1223826361
