### ISSUE TITLE
Default Unity ToString implementations can be misleading

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#216]
```clojure
user=> (str (UnityEngine.Vector3. 0.01 0.01 0.01))
"(0.0, 0.0, 0.0)"

user=> (pr-str (UnityEngine.Vector3. 0.01 0.01 0.01))
"#unity/Vector3 [0.01 0.01 0.01]"
```

Not sure if this is our place to intervene, but that first one is really unfortunate. A suggestion came up on the Gitter to make `arcadia.core/log` use `pr-str` instead of `str`. This resolves issues like the one mentioned above, while bringing `log` in line with our REPL output (which uses `pr-str`), but also has the effect of obscuring some information at times.

```clojure
user=> (def o (UnityEngine.GameObject. "fish"))
#'user/o
user=> (str o)
"fish (UnityEngine.GameObject)"
user=> (pr-str o)
"#unity/GameObject -23820"
```

**Comment by jeaye** [comment]
After being bitten by the `v3` `log` issue, I'd prefer `pr-str` here. I agree that `str` gives better output for `GameObject`, but `pr-str` doesn't give output which is _wrong_. Arguably, the current implementation does.

Specifying the type, as `pr-str` does, is also quite helpful. The existing `log` would output the same for `(v3 1.0)` and `(repeat 3 1.0)`.

**Comment by nasser** [comment]
We're going to keep `log` the way it is and possibly introduce another logging function down the line that bottoms out in `pr-str`.
