### ISSUE TITLE
`placeholder` function

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#217]
Unity's object model includes a kind of "typed null" object. Every class that inherits from `UnityEngine.Object` has a "null reference" instance that has that class as its type, but an instance id of 0.  This null reference is used by Unity to represent *absent* objects of a particular type, encoding what type the value *was* or *will be*. Frustratingly, this value is truthy.

Unity uses this "typed null" in a variety of places, notably the Inspector where it uses "typed null" references to render the UI that allows the user to drag and drop objects of that type.

![](http://nas.sr/teaching/2016/game-design/unity-cheat-sheet/images/component-variable.gif)

Although not usual in Unity programming, we can generate "typed nulls" from code. I am suggesting adding a function to the core API that does this, called `placeholder` here, though I am not committed to the name.

`placeholder` takes a type and returns the "typed null" reference from that type.

```clojure
user=> (import [UnityEngine GameObject Transform Rigidbody BoxCollider])
UnityEngine.BoxCollider
user=> (placeholder GameObject)
#unity/Object 0
user=> (placeholder Transform)
#unity/Transform 0
user=> (placeholder BoxCollider)
#unity/BoxCollider 0
```

The primary use case is in state maps, where the *value* of a Unity GameObject or Component reference is not known at code evaluation time, but will be configured in the inspector later.

```clojure
(doto (GameObject. "foo")
  (set-state! :target (placeholder Transform))
  (set-state! :enemy (placeholder GameObject))
  (set-state! :boundaries (placeholder BoxCollider))
  (set-state! :health 100)
  (set-state! :death-message "Oh No!"))
```

![](https://files.gitter.im/arcadia-unity/Arcadia/ERxn/Screen-Shot-2017-03-15-at-11.50.46-AM.png)

Here, the foo GameObject's state references *some* `Transform` in its `:target` key, *some* `GameObject` in its `:enemy` key, and *some* `BoxCollider` in its `:boundaries` key. The particular values can be dropped in via the inspector. There is currently no easy way to express this.

A note on the current sketch of the [implementation](https://gist.github.com/nasser/38eb43d6b14a0a38c358186ee7716fb6): generating a "typed null" `GameObject` is tricky, so it just returns a "typed null" `UnityEngine.Object`. This functions for the UI use case, but is something that can and should be addressed with additional work.

**Comment by jeaye** [comment]
How does using `UnityEngine.Object` affect the usage of the state? For example, if I pull out that object from my state and try to add a component to it, or get a component from it, will that work?

```clojure
(def obj (GameObject. "foo"))
(set-state! obj :enemy (placeholder GameObject))

;; set enemy in inspector

(cmpt+ (:enemy obj) CharacterController)
```

Arcadia could generate a single empty `GameObject`, on startup, and then use it as the value if the placeholder type is `GameObject`.

**Comment by nasser** [comment]
Our editor integration story has deviated significantly from what it was when this issue was opened and it is no longer relevant. Closing.
