### ISSUE TITLE
Cannot populate arrays

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#22]
```clojure
(populate! {:name "Trumpax"
            :mesh-renderer [{:materials [{:main-texture some-texture
                                          :color Color/red}]}]})
```

Does not work because there is no hydrator for `UnityEngine.Material[]`, which is the type of [Renderer.materials](http://docs.unity3d.com/ScriptReference/Renderer-materials.html).

**Comment by timsgardner** [comment]
hydrate is lib
