### ISSUE TITLE
ArcadiaState var deserialization broken

### ISSUE THREAD

**Issue by selfsame** [arcadia-unity/Arcadia#232]
vars are deserialized as a clojure.lang.PersistentList like `(var foo/bar)`

**Comment by nasser** [comment]
Is this a correct example case?

```clojure
(set-state! gobj :foo #'foo/bar)
```

**Comment by selfsame** [comment]
Yes, which shows up once the state has been serialized.  Clojure handles `(read-string "#'foo/bar")` as `(var foo/bar)`, so this is the result of https://github.com/arcadia-unity/Arcadia/blob/develop/Source/arcadia/internal/state_help.clj#L22

Adding an eval to that line breaks the `#unity/foo -123124` db references, which is odd because `(eval (read-string "#unity/transform 12341"))` works just fine

**Comment by timsgardner** [comment]
There's a lot of other branches open now waiting to be merged in, and I think this may be solved on some or many of them. I will take a look.

**Comment by timsgardner** [comment]
closed as of 22b59f08715ee1d46fff655421571b341b605582, far as I can tell.
