### ISSUE TITLE
arcadia.linear/v4 functions buggy

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#234]
```clojure
(v4+ (v4 1 5 6 9) (v4 1 5 6 9))
;; #unity/Vector4 [18.0 2.0 10.0 12.0]
```

Expected `#unity/Vector4 [2.0 10.0 12.0 18.0]`. Looks like components are being swapped around.

**Comment by nasser** [comment]
This is a side-effect of the alphabetical field sorting in `arcadia.literals`. These functions actually work fine.

```clojure
(v4+ (v4 1 5 6 9) (v4 1 5 6 9))
;; #unity/Vector4 [18.0 2.0 10.0 12.0]

(.x (v4+ (v4 1 5 6 9) (v4 1 5 6 9)))
;; 2.0

(.y (v4+ (v4 1 5 6 9) (v4 1 5 6 9)))
;; 10.0

(.z (v4+ (v4 1 5 6 9) (v4 1 5 6 9)))
;; 12.0

(.w (v4+ (v4 1 5 6 9) (v4 1 5 6 9)))
;; 18.0
```

Simpler examples illustrate this as well

```clojure
(v4 1 2 3 4)
;; #unity/Vector4 [4.0 1.0 2.0 3.0]

(UnityEngine.Quaternion. 1 2 3 4)
;; #unity/Quaternion [4.0 1.0 2.0 3.0]
```

`arcadia.literals` needs to be resisted to see if this can be addressed. At the very least this confusing behavior needs to be documented.

**Comment by timsgardner** [comment]
seems like a non-issue
