### ISSUE TITLE
clojure.core/require allocates every time

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#236]
Following @selfsame's [analysis](https://gitter.im/arcadia-unity/Arcadia?at=594547c3caf4d68d6f438830) it seems `require`'s internal list operations turn out to allocate memory even when loading an already-loaded namespace. This changes my perception of the cost of require as a one-time thing, and makes the parts of Arcadia that depend on namespace loading costlier as a result.

Possible solution: our own custom zero-alloc require method that checks to see if the requested namespace is already loaded and bails if it is, otherwise falling back to the usual code path.

**Comment by selfsame** [comment]
redundant `require`s will allocate 3.7kb and on my machine take about `.7ms`

I think the plan here should be to ensure the new `quickquire` fn is always loaded, so it itself can be invoked without a require.

**Comment by nasser** [comment]
@selfsame just to be totally clear, that's 3.7kb *per invocation*?

I would honestly prefer `quickquire` to be implemented in C# to avoid namespace loading/allocation shenanigans.

**Comment by timsgardner** [comment]
If you really want to move `quickquire` to C# go ahead, I say if it ain't broke don't fix it.
Is there anything more to say about this one? Rewriting `require` seems sketchy and unnecessary, with `quickquire` we have a solution that seems to work fine and a lot of other battles to fight.

**Comment by timsgardner** [comment]
updated ArcadiaState to use `Arcadia.Util.require` throughout, which uses `quickquire`
