### ISSUE TITLE
Eval closure in C#?

### ISSUE THREAD

**Issue by srfoster** [arcadia-unity/Arcadia#240]
I like the REPL.  However, I have a game (CodeSpells) where people write code in-game.  I'm considering switching the in-game language from JavaScript to Clojure.  Would I be able to evaluate the Clojure code players write in my C# code?  I don't want players to have to write their Clojure code in an external editor.

**Comment by jblouir** [comment]
You should be able to use the clojure form (load-string "(def x 1)") if I'm understanding the problem correctly?

**Comment by jblouir** [comment]
load-string can load and execute clojure code while the system is running

**Comment by jblouir** [comment]
https://clojuredocs.org/clojure.core/load-string

**Comment by srfoster** [comment]
Thanks for the response.  That looks like a Clojure way of evaluating Clojure code.  But I'm looking for a C# way of evaluating Clojure code.  Some thing I could do from inside a Unity Monobehaviour, for example:

```
void Awake(){
    SomeMagicThing.EvaluateClojure("(log \"hi\")");
}
```

**Comment by nasser** [comment]
```cs
using clojure.lang;

public class SomeMagicThing
{
    public static object EvaluateClojure(string source)
    {
        return Compiler.eval(RT.readString(source));
    }
}
```

Haven't had a chance to test it but that *should* work, depending on what you want to do.

**Comment by nasser** [comment]
Closing for now, but hop on gitter.im/arcadia-unity/Arcadia if you have more questions! Everyone is very nice and quick to answer.
