### ISSUE TITLE
Broken Hook Serialization

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#250]
Set up code

```clojure
(defn mover [^GameObject go k]
  (when (Input/GetMouseButton 0)
    (let [press3d (.ScreenToWorldPoint Camera/main Input/mousePosition)
          press2d (Vector2. (.x press3d) (.y press3d))
          dir (v2- press2d
                   (.position (cmpt go Rigidbody2D)))
          dirnorm (.normalized dir)
          dirmag (.magnitude dir)]
      (move-2d go (v2* dirnorm (* 0.05 dirmag))))))

(def movement-role
  {:state 0.1
   :fixed-update #'mover})

(role+ (object-named "Player") ::movement movement-role)
```

Seeing this in the inspector

![image](https://user-images.githubusercontent.com/412966/29837887-859158ee-8cc7-11e7-90de-6bcb1a09ec82.png)

Not sure when this broke, but the project has been closed and opened and export had been attempted multiple times.

**Comment by timsgardner** [comment]
having trouble replicating this bug (code seems to work). More specifically:

```clojure
(ns issue-250.core
  (:use arcadia.core
        arcadia.linear)
  (:import [UnityEngine Input Vector2 Rigidbody2D GameObject Camera]))

(defn move-2d [x y])

(defn mover [^GameObject go k]
  (when (Input/GetMouseButton 0)
    (let [press3d (.ScreenToWorldPoint Camera/main Input/mousePosition)
          press2d (Vector2. (.x press3d) (.y press3d))
          dir (v2- press2d
                   (.position (cmpt go Rigidbody2D)))
          dirnorm (.normalized dir)
          dirmag (.magnitude dir)]
      (move-2d go (v2* dirnorm (* 0.05 dirmag))))))

(def movement-role
  {:state 0.1
   :fixed-update #'mover})

;; (role+ (object-named "Player") ::movement movement-role)
```
This survives scene save, closing & reopening unity. Haven't tried export yet, is this just an export thing?

**Comment by nasser** [comment]
It's hard to reproduce, its some kind of ordering/timing bug. It might be export related, I am not sure. Can you try exporting and see if that breaks it for you as well?

**Comment by timsgardner** [comment]
![image](https://user-images.githubusercontent.com/451342/30347904-92513e72-97db-11e7-96bc-ba2220fbfc03.png)

**Comment by timsgardner** [comment]
This is tested on `pass-keys` 336f2dcba06a7d710cfe64fbf34f2574399e45b3, which I'm not sure is even pushed out yet, so that might be an ish. Can you get me the hash of the commit you're on? And I guess a zip of the project itself?

**Comment by timsgardner** [comment]
The bug you're looking at does look like some derpy destructuring problem - fast fix. I recognize the structure you're printing out there

**Comment by nasser** [comment]
Were you able to run the built project? Does it use hooks and state in the scene?

I can try and reproduce the project, might take a minute.

**Comment by timsgardner** [comment]
I'm pretty sure this is a bug with trying to reopen a scene that was saved with an obsolete serialization format. Tempted to just close it.
