### ISSUE TITLE
socket repl should start by default

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#253]
obviously

**Comment by nasser** [comment]
Blocking on #238 finishing and being confirmed stable

**Comment by timsgardner** [comment]
Why is it blocking on that? Why not just do it?

**Comment by timsgardner** [comment]
what we should have is a flag somewhere for whether or not we're exporting

**Comment by timsgardner** [comment]
As of 8f5b9f7d8110aada19b87bb391976d0929c925c1, socket repl starts by default when in editor. Can still be explicitly enabled/disabled in config via `:socket-repl` entry.
