### ISSUE TITLE
Support for Godot engine and Mono

### ISSUE THREAD

**Issue by abhi18av** [arcadia-unity/Arcadia#258]
Hi team Arcadia

I admire the kind of work that you guys have put into `Unity` and `ClojureCLR`! 

I'd like to propose an alternative backend for Arcadia ( or a separate package ) targeting the [Godot game engine](https://godotengine.org/). I'd definitely  love to see `ClojureCLR` more in the limelight, especially in the context of cross platform gaming and `.NET` stuff 

[The recent introduction of mono in Godot](https://godotengine.org/article/introducing-csharp-godot) made me relate these two projects. 

Please do look into it :)

P.S. Feel free to close this "issue".

**Comment by nasser** [comment]
I love this idea. Likely, it would be a separate package because Arcadia is deeply integrated into Unity and optimized for that environment, but all the ClojureCLR work we've done here – especially MAGE and MAGIC – should still be relevant.

Closing, but thanks for the heads up!

**Comment by abhi18av** [comment]
You're most welcome @nasser ! ;)

**Comment by timsgardner** [comment]
@selfsame's got it: https://github.com/arcadia-unity/ArcadiaGodot

**Comment by abhi18av** [comment]
@timsgardner @selfsame awesome!

But I do see that there's a lot of work that could be done once the Godot Engine reaches 3.0 stable :)
