### ISSUE TITLE
csharp files pulled in from clojars are not automatically detected

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#263]
When the dependency `[timsg.scene-var "0.1.0-SNAPSHOT"]` is specified in `configuration.edn` and pulled in, among other things the file `Assets/Arcadia/Libraries/c_sharp/SceneVarAnchor.cs` shows up, but Unity doesn't detect the type and it can't be `import`ed. If you move `SceneVarAnchor.cs` around a little in the editor, Unity picks up on it and you can `import` it.

**Comment by nasser** [comment]
Did you give the Unity editor focus before you tried to `import` it?

**Comment by timsgardner** [comment]
No longer relevant as we have moved to Nuget
