### ISSUE TITLE
`null-obj`, `obj-nil` need scrubbing

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#269]
These are among the most ancient parts of the codebase. We need something that does their work, but their names are terrible and confusing, especially taken together, and a more streamlined policy is probably better.

We need a function that takes an object _or nil_. If it's passed nil, it should return nil. Otherwise it should return the object if and only if the object is not Unity `null` via `UnityEngine.Object/op_Equality`, and nil otherwise.

So more a filter than a predicate. This function is easy to define but hard to name, because it's a response to a logically ridiculous situation (thingy nothing). `alive`?

**Comment by timsgardner** [comment]
Another possibility, or another function, is one that takes anything and always returns it unless it's a null GameObject, in which case it returns nil. This is basically the same idea, but it can take anything (not just GameObjects).

**Comment by timsgardner** [comment]
I'm increasingly thinking the right answer is basically `identity` except null GameObjects become `nil`. Still no idea what it should be called.

**Comment by timsgardner** [comment]
`scrub`?

**Comment by selfsame** [comment]
I'd propose a `null-obj?` predicate that returns `true` or `false`

**Comment by nasser** [comment]
Talking to @timsgardner right now: Maybe `pun`? To reference nil punning?

**Comment by timsgardner** [comment]
closed in 4a786024af5a0123e61c44f34aa4d29df830bd42
