### ISSUE TITLE
ArcadiaState doesn't add new keys before hook

### ISSUE THREAD

**Issue by pjago** [arcadia-unity/Arcadia#274]
This issue is mainly related with my repl workflow.

I am seeing this behaviour where if I instantiate a fresh object out of my resources, and try to do a `state+` on it, it adds the state, but right after ending the function (where I instantiate), somewhere in a event it removes it! haha

I tested and it seems that if I add a `hook+`  on the the same key, before `state+`, it will actually keep the state. Peharps it has to with the `RefreshAll` call after `Add` or something else important that hooks do.
I couldn't figure out exactly but I think the bug is there.

**Comment by pjago** [comment]
A similar issue seems to be happening when the object is instantiated while inactive.
But the state is there, and once the object is active I can access, even if I set it inactive later.

**Comment by timsgardner** [comment]
Closed; or at least, I can't replicate the behavior. If it's still a problem please attach code/instructions to recreate minimalish case, thanks.
