### ISSUE TITLE
empty `ArcadiaBehaviour` breaks in build

### ISSUE THREAD

**Issue by selfsame** [arcadia-unity/Arcadia#276]
scenario:
* had an empty hook on an object I was instantiating
* after instantiation code added a fn with `hook+`
* in build error was thrown about "could not find reader for type Object"

Temporary solution was to find any empty hooks in project and delete from prefabs.

**Comment by timsgardner** [comment]
Thanks for the report, can you clarify what an empty hook is?

**Comment by selfsame** [comment]
a hook with no functions attached

**Comment by timsgardner** [comment]
Can't replicate this bug with `hook+` followed by `hook-` followed by export. Closing pending reproducible case.

**Comment by selfsame** [comment]
hmm yeah can't reproduce it now, guess it got fixed
