### ISSUE TITLE
cleanup visa vi 2018.2 removing deprecated networking system

### ISSUE THREAD

**Issue by Mechrophile** [arcadia-unity/Arcadia#280]
Once we move to 2018, we'll need to remove some old hooks. 

![image](https://user-images.githubusercontent.com/2494198/39828099-e22b6f18-5387-11e8-80f0-3acc39365c8f.png)

OnDisconnectedFromServerHook
OnFailedToConnectHook
OnFailedToConnectToMasterServerHook
OnMasterServerEventHook
OnNetworkInstantiateHook
OnPlayerConnectedHook
OnPlayerDisconnectedHook
OnSerializeNetworkViewHook
OnSerializeNetworkViewHook

**Comment by nasser** [comment]
Fixed in 656e82d
