### ISSUE TITLE
Using on-pointer-click in a role makes the spec for defrole fail

### ISSUE THREAD

**Issue by Saikyun** [arcadia-unity/Arcadia#284]
When trying to define a role using on-pointer-click, such as:
```
(defrole button
  :state {:callback nil}
  (on-pointer-click
   [obj k heh]
    (log "hello")
   ))
```
you get a spec error from the spec of defrole in arcadia.core, telling you that it can't handle 3 args.

The [spec](https://github.com/arcadia-unity/Arcadia/blob/390b01f3d479149081b085f00fc6dea510940f6e/Source/arcadia/core.clj#L756) seems to try to deal with multiple args, but something goes wrong.

The ugly hotfix is to remove the last part of the spec, making it look like:
```
(s/def ::defrole-impl
  (s/and
    (s/cat
      :name (s/and symbol? #(contains? hook-types (keyword (name %))))
      :args (s/coll-of any? :kind vector?)
      :body (s/* any?))
    (fn [{:keys [args], nm :name}]
      (= (count args) (+ 2 (count (hook->args (keyword (name nm)))))))))
```

**Comment by timsgardner** [comment]
Thanks for the catch, we're treating messages and interface-messages inconsistently in arcadia.core. Addressing it now.
