### ISSUE TITLE
inf-clojure repl crashes on errors

### ISSUE THREAD

**Issue by Saikyun** [arcadia-unity/Arcadia#293]
Often when trying random stuff in the inf-clojue repl in Emacs, it just dies.
Example:
```clojure
game.core=> (map (fn [a b] b) [1 2 3])
Process inf-clojure connection broken by remote peer
```

This didn't happen before the move to Unity 2018.

**Comment by timsgardner** [comment]
closed as of 1c7c165f1b815494fa8659c887851dc5b08e4e32
