### ISSUE TITLE
Type or namespace clojure not found

### ISSUE THREAD

**Issue by srfoster** [arcadia-unity/Arcadia#295]
I tried going through the getting started guide with the latest version of Unity.

A couple of things I noticed:

1) Is the API compatibility setting panel gone?  I haven't used Unity in a while.  It used to be there.  But now it's not.  Or it moved.  (Or I'm blind?)  Anyway, maybe it's worth updating the docs if that's different now.

2) After cloning the arcadia repo into the Assets directory, I got compile errors -- chiefly: type or namespace clojure not found.  Did I miss a step?

BTW, I'm on OSX.

**Comment by nasser** [comment]
> Is the API compatibility setting panel gone? I haven't used Unity in a while. It used to be there. But now it's not. Or it moved. (Or I'm blind?) Anyway, maybe it's worth updating the docs if that's different now.

2018.1 introduces an updated version of Mono, so its likely what you're looking for has moved or changed. Which panel exactly do you mean?

> After cloning the arcadia repo into the Assets directory, I got compile errors -- chiefly: type or namespace clojure not found. Did I miss a step?

Hm, can you paste the exact errors you got? Arcadia should work fine on 2018.1 on OSX.

**Comment by nasser** [comment]
Updated USAGE to reflect the content from [the wiki](https://github.com/arcadia-unity/Arcadia/wiki/Getting-Started#mono-runtime).
