### ISSUE TITLE
Running inf-clojure--process-response twice breaks itself

### ISSUE THREAD

**Issue by Saikyun** [arcadia-unity/Arcadia#302]
Running the elisp function `inf-clojure--process-response` only works once. If you run it a second time you will get an empty string returned, and the result instead printed out in the repl. This is a problem because a lot of the functionality in `inf-clojure` is dependent on `inf-clojure--process-response`, and when writing new editor functionality the function is essential.

In these examples "user=>" represents the clojure repl.
```emacs-lisp
(inf-clojure--process-response "1" (inf-clojure-proc))
;; returns "1
;; "
;; user=>             ;; (nothing happens here
```
Note the newline in the result of "inf-clojure--process-response", this might be a piece of the puzzle.

Now let's run `inf-clojure--process-response` again.
```emacs-lisp
(inf-clojure--process-response "1" (inf-clojure-proc))
;; returns ""
;; user=> 1
;; user=>
```
One way to "solve" this is to evaluate something in the repl
```emacs-lisp
;; user=> :wat
;; user=> :wat
```
For some reason it will print the prompt again, which I also think is a part of the problem, since it normally looks like this:
```emacs-lisp
;; user=> :wat
;; :wat
```
Now when running the elisp function again:
```emacs-lisp
(inf-clojure--process-response "1" (inf-clojure-proc))
;; returns "1
;; "
;; user=>             ;; (nothing happens here
```
We get the expected result.

**Comment by Saikyun** [comment]
Even when disabling all other emacs packages (except clojure, inf-clojure and the arcadia-repl-functions) using Emacs 26.1 I get the same error.

**Comment by timsgardner** [comment]
Hey, this seems like an inf-clojure bug rather than an Arcadia bug? Closing for now

**Comment by Saikyun** [comment]
It's not! Maybe you didn't read it on gitter, but it's because of the
custom read function you built. If I use the regular one there aren't any
issues. This is also related to the issue with the repl getting stuck on
`inf-clojure-eval-buffer`. So I "solved" it by using the old read function,
with the downside being potential deadlocks like you described.

Den mån 1 okt. 2018 21:21Tims Gardner <notifications@github.com> skrev:
