### ISSUE TITLE
Serialization should be edn

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#304]
`arcadia.internal.state-help/deserialize` uses `read-string` rather than `edn/read-string`, this seems wrong if we're really serializing as edn

**Comment by timsgardner** [comment]
Similarly, we should have a policy about serializing and deserializing things like arrays. Their printed representation (ToString) isn't good enough.

**Comment by nasser** [comment]
`arcadia.internal.state-help/deserialize` now uses `edn/read-string` and a mechanism is in place to pivot away from EDN down the line if we need to in a manner that will not break old code.
