### ISSUE TITLE
can't AOT internal namespaces [beta - windows]

### ISSUE THREAD

**Issue by selfsame** [arcadia-unity/Arcadia#315]
After using the `Arcadia > Build > Internal Namespaces` menu command and compiling the dlls, i get https://gist.github.com/selfsame/1345efcfcfe59e6a0215acd74794a5db

Windows 7
Arcadia 8395246a177b70295c3de6f928d6e993456a3792
Unity  version 2018.2.7f1

**Comment by meta-meta** [comment]
I tried this today, same error when pressing play.

Windows 10
Unity: 2018.2.8f1
Arcadia `dcfb757`

**Comment by nasser** [comment]
Fixed in d1f9a589cc9382ba06da0477b0843cfe52e03c56
