### ISSUE TITLE
Socket REPL default port may conflict with Unity Editor on some Linuxen

### ISSUE THREAD

**Issue by sogaiu** [arcadia-unity/Arcadia#319]
IIUC, the default port for the socket REPL is 5555.  On Manjaro Linux (but not macos or Windows 7), the Unity Editor listens on tcp4 port 5555.  Instead of only one or the other winning out for the tcp4 port, the Unity Editor gets the tcp4 port and the socket REPL gets the tcp6 port:

```
# tcp 4
$ telnet 127.0.0.1 5555
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
014-01-02 15:28:22.957823
```

```
# tcp 6
$ telnet ::1 5555
Trying ::1...
Connected to ::1.
Escape character is '^]'.
user=> 
```

I'd noticed that on occasion, trying to connect to the socket REPL using arcadia-repl in Emacs yielded a string that contained characters like: '014-01-02 15:28:22.957823'.  No clues as to why that happens apart from possibly Emacs sometimes deciding to connect via the tcp4 port.

I tried changing :address and :port via configuration.edn's :socket-repl.  Some things I tried and results are:

- :port 8888 
   => socket REPL listens on port 8888, but strangely still uses IPv6

- :address '127.0.0.1' 
   => socket REPL still uses IPv6

- :port 8888 :address '192.168.1.2' 
   => socket REPL uses IPv4 and listens on port 8888

I haven't tweaked any network settings such as /etc/hosts or /etc/resolv.conf (managed by NetworkManager anyway).  FWIW, here's my /etc/hosts:

```
127.0.0.1       localhost
127.0.1.1       user-pc
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

All of my testing was using selfsame's procjam2018, FWIW, so I think that's using some version of the develop branch and at least one of the the Unity Editor versions is 2018.2.11f1.

**Comment by sogaiu** [comment]
I tried having something else listening on tcp4 port 5555 before starting the Unity Editor.  Unity Editor listens on 5556 instead (perhaps it keeps trying higher numbers?).

I didn't succeed in turning up what it is that Unity Editor is doing with that port, nor how to to configure it to leave that port alone.  May be someone else will have some luck.

Is it possible to choose a port other than 5555 as the default port?  This port number appears to be used by a number of different parties (e.g. Android emulator, Clojure socket REPL, Unity Editor, and I wouldn't be surprised to find others), so may be it's not such a great choice.  WDYT?

**Comment by sogaiu** [comment]
I found the following:

  https://dev.clojure.org/jira/browse/NREPL-83

It has the following description:

```
starts-server defaults to binding to 'localhost' which causes it to accept connections only on one of IPv4 or IPv6, depending on what 'localhost' is resolved to. The order in which IPv4 and IPv6 addresses are returned by the resolver may differ between applications on a single host, causing connections to fail because the client chooses a different protocol. It is preferable to use the 'anylocal' address so that dual stacks accept connections on both protocols.
```

**Comment by nasser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reproduce issue #102](https://trello.com/c/YaY7Y96Q/16-reproduce-issue-102)

**Comment by nasser** [comment]
We've moved the socket REPL port to 37220 which should dodge this collision. We can look into binding to localhost differently if this continues to be an issue.
