### ISSUE TITLE
InvalidOperationException: Unable to resolve symbol: Coroutiner in this context on Prepare Build

### ISSUE THREAD

**Issue by TobiasMorell** [arcadia-unity/Arcadia#322]
When I try to build my solution for release using the Arcadia --> Build --> Prepare Export I get the following exception:

> InvalidOperationException: Unable to resolve symbol: Coroutiner in this context
clojure.lang.Compiler.ResolveIn (clojure.lang.Namespace n, clojure.lang.Symbol symbol, System.Boolean allowPrivate) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.Compiler.Resolve (clojure.lang.Symbol symbol) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.Compiler.AnalyzeSymbol (clojure.lang.Symbol symbol) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.Compiler.Analyze (clojure.lang.CljCompiler.Ast.ParserContext pcontext, System.Object form, System.String name) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
Rethrow as CompilerException: System.InvalidOperationException: Unable to resolve symbol: Coroutiner in this context
clojure.lang.Compiler.ResolveIn (clojure.lang.Namespace n, clojure.lang.Symbol symbol, System.Boolean allowPrivate) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.Compiler.Resolve (clojure.lang.Symbol symbol) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.Compiler.AnalyzeSymbol (clojure.lang.Symbol symbol) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.Compiler.Analyze (clojure.lang.CljCompiler.Ast.ParserContext pcontext, System.Object form, System.String name) (at <e5c1049893bf4d6f8893a41079c4a366>:0 , compiling: (game/unity.clj:56:10))
clojure/core$load_libfn__61233__61237.invoke () (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure/core$load_lib__61244.invokeStatic (System.Object , System.Object , clojure.lang.ISeq ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure/core$load_lib__61244.doInvoke (System.Object , System.Object , System.Object ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure.lang.RestFn.applyTo (clojure.lang.ISeq arglist) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure/core$apply__56552.invokeStatic (System.Object , System.Object , System.Object ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure/core$apply__56552.invoke (System.Object , System.Object , System.Object ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure/core$load_libs__61268.invokeStatic (clojure.lang.ISeq ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure/core$load_libs__61268.doInvoke (System.Object ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure.lang.RestFn.applyTo (clojure.lang.ISeq arglist) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure/core$apply__56552.invokeStatic (System.Object , System.Object , System.Object ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure/core$apply__56552.invoke (System.Object , System.Object , System.Object ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure/core$require__61288.invokeStatic (clojure.lang.ISeq ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure/core$require__61288.doInvoke (System.Object ) (at <2eac4bec9d764b48a665a9fdc00d6fe6>:0)
clojure.lang.RestFn.invoke (System.Object arg1) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
arcadia/compiler$aot_namespacesfn__25150__25158.invoke () (at <1f7bbbe4cda74303a40ef7665d47684a>:0)
arcadia/compiler$aot_namespaces__25168.invokeStatic (System.Object , System.Object , System.Object ) (at <1f7bbbe4cda74303a40ef7665d47684a>:0)
arcadia/compiler$aot_namespaces__25168.invoke (System.Object , System.Object , System.Object ) (at <1f7bbbe4cda74303a40ef7665d47684a>:0)
Arcadia.Util.Invoke (clojure.lang.Var v, System.Object a, System.Object b, System.Object c) (at Assets/Arcadia/Helpers/Util.cs:59)
Arcadia.BuildPipeline.CompileNamespacesToFolder (System.Collections.IEnumerable userNameSpaces, System.String targetFolder) (at Assets/Arcadia/Editor/BuildPipeline.cs:130)
Arcadia.BuildPipeline.PrepareExport () (at Assets/Arcadia/Editor/BuildPipeline.cs:173)

The full solution is available in [this github repository](https://github.com/spPT-2018/language-benchmark/tree/master/arcadia-test). The project runs fine inside the editor.

I can also build using Unity's build tool, but when starting the game it logs the following:

> FileNotFoundException: Could not locate clojure.core.cljc.dll or clojure/core.cljc on load path.
  at clojure.lang.RT.load (System.String relativePath, System.Boolean failIfNotFound) [0x001a2] in <e5c1049893bf4d6f8893a41079c4a366>:0 
  at clojure.lang.RT.load (System.String relativePath) [0x00000] in <e5c1049893bf4d6f8893a41079c4a366>:0 
  at clojure.lang.RT.DoInit () [0x00000] in <e5c1049893bf4d6f8893a41079c4a366>:0 
  at clojure.lang.RT..cctor () [0x01f3d] in <e5c1049893bf4d6f8893a41079c4a366>:0 
Rethrow as TypeInitializationException: The type initializer for 'clojure.lang.RT' threw an exception.
  at Arcadia.Util.require (System.String s) [0x0000a] in <acd872fbdee644fe8289b5feccfa824c>:0 
  at ArcadiaBehaviour.InitializeOwnVars () [0x00006] in <acd872fbdee644fe8289b5feccfa824c>:0 
  at ArcadiaBehaviour.FullInit () [0x0000c] in <acd872fbdee644fe8289b5feccfa824c>:0 
  at ArcadiaBehaviour.Awake () [0x00000] in <acd872fbdee644fe8289b5feccfa824c>:0 
(Filename: <e5c1049893bf4d6f8893a41079c4a366> Line: 0)
FileNotFoundException: Could not locate clojure.core.cljc.dll or clojure/core.cljc on load path.
  at clojure.lang.RT.load (System.String relativePath, System.Boolean failIfNotFound) [0x001a2] in <e5c1049893bf4d6f8893a41079c4a366>:0 
  at clojure.lang.RT.load (System.String relativePath) [0x00000] in <e5c1049893bf4d6f8893a41079c4a366>:0 
  at clojure.lang.RT.DoInit () [0x00000] in <e5c1049893bf4d6f8893a41079c4a366>:0 
  at clojure.lang.RT..cctor () [0x01f3d] in <e5c1049893bf4d6f8893a41079c4a366>:0 
Rethrow as TypeInitializationException: The type initializer for 'clojure.lang.RT' threw an exception.
  at Arcadia.Util.require (System.String s) [0x0000a] in <acd872fbdee644fe8289b5feccfa824c>:0 
  at ArcadiaState.InitializeOwnVars () [0x00011] in <acd872fbdee644fe8289b5feccfa824c>:0 
  at ArcadiaState.Initialize () [0x0000c] in <acd872fbdee644fe8289b5feccfa824c>:0 
  at ArcadiaState.Awake () [0x00000] in <acd872fbdee644fe8289b5feccfa824c>:0 
(Filename: <e5c1049893bf4d6f8893a41079c4a366> Line: 0)

**Comment by nasser** [comment]
It looks like you didn't import the `Coroutiner` class in [unity.clj](https://github.com/spPT-2018/language-benchmark/blob/master/arcadia-test/Assets/game/unity.clj). You might have `import`ed the `Coroutiner` class in the REPL, but the AOT compiler needs an `:import` declaration in the `ns` form to build the `.dll` files correctly. It's also not clear where `Coroutiner` is defined.

Can you try adding `(:import ...)` to unity.clj's `ns` form, where `...` is  the fully qualified name of the `Coroutiner` class and see if it works?

**Comment by TobiasMorell** [comment]
I had one of my colleagues follow your suggestion and push to the repo, after which I tried to build on my machine again. The error stated above disappeard, but was replaced by another one:

> NullReferenceException: Object reference not set to an instance of an object
clojure.lang.Util.NameForType (System.Type t) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.Namespace.importClass (System.Type t) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
game/unity$loading__18057__auto____27931__27934.invokeStatic () (at <11d225754d5a4770b2e0f788ef7d4acd>:0)
game/unity$loading__18057__auto____27931__27934.invoke () (at <11d225754d5a4770b2e0f788ef7d4acd>:0)
clojure.lang.AFn.ApplyToHelper (clojure.lang.IFn fn, clojure.lang.ISeq argList) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.AFn.applyTo (clojure.lang.ISeq arglist) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.CljCompiler.Ast.InvokeExpr.Eval () (at <e5c1049893bf4d6f8893a41079c4a366>:0)
Rethrow as CompilerException: System.NullReferenceException: Object reference not set to an instance of an object
clojure.lang.Util.NameForType (System.Type t) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.Namespace.importClass (System.Type t) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
game/unity$loading__18057__auto____27931__27934.invokeStatic () (at <11d225754d5a4770b2e0f788ef7d4acd>:0)
game/unity$loading__18057__auto____27931__27934.invoke () (at <11d225754d5a4770b2e0f788ef7d4acd>:0)
clojure.lang.AFn.ApplyToHelper (clojure.lang.IFn fn, clojure.lang.ISeq argList) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.AFn.applyTo (clojure.lang.ISeq arglist) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure.lang.CljCompiler.Ast.InvokeExpr.Eval () (at <e5c1049893bf4d6f8893a41079c4a366>:0 , compiling: (unity.clj:3:2))
clojure/core$load_libfn__18229__18233.invoke () (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure/core$load_lib__18240.invokeStatic (System.Object , System.Object , clojure.lang.ISeq ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure/core$load_lib__18240.doInvoke (System.Object , System.Object , System.Object ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure.lang.RestFn.applyTo (clojure.lang.ISeq arglist) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure/core$apply__13548.invokeStatic (System.Object , System.Object , System.Object ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure/core$apply__13548.invoke (System.Object , System.Object , System.Object ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure/core$load_libs__18264.invokeStatic (clojure.lang.ISeq ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure/core$load_libs__18264.doInvoke (System.Object ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure.lang.RestFn.applyTo (clojure.lang.ISeq arglist) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
clojure/core$apply__13548.invokeStatic (System.Object , System.Object , System.Object ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure/core$apply__13548.invoke (System.Object , System.Object , System.Object ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure/core$require__18284.invokeStatic (clojure.lang.ISeq ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure/core$require__18284.doInvoke (System.Object ) (at <f8cb67f9668d4eb2aa581660412446c2>:0)
clojure.lang.RestFn.invoke (System.Object arg1) (at <e5c1049893bf4d6f8893a41079c4a366>:0)
arcadia/compiler$aot_namespacesfn__14275__14283.invoke () (at <043824aa7b8047829bd792fe24ce6f7d>:0)
arcadia/compiler$aot_namespaces__14293.invokeStatic (System.Object , System.Object , System.Object ) (at <043824aa7b8047829bd792fe24ce6f7d>:0)
arcadia/compiler$aot_namespaces__14293.invoke (System.Object , System.Object , System.Object ) (at <043824aa7b8047829bd792fe24ce6f7d>:0)
Arcadia.Util.Invoke (clojure.lang.Var v, System.Object a, System.Object b, System.Object c) (at Assets/Arcadia/Helpers/Util.cs:59)
Arcadia.BuildPipeline.CompileNamespacesToFolder (System.Collections.IEnumerable userNameSpaces, System.String targetFolder) (at Assets/Arcadia/Editor/BuildPipeline.cs:130)
Arcadia.BuildPipeline.PrepareExport () (at Assets/Arcadia/Editor/BuildPipeline.cs:173)

**Comment by nasser** [comment]
Hm, can you provide the full source of the file you're trying to compile? I also couldn't find the `Coroutiner` class anywhere in your repo. Can you point me to the file that defines that type?

**Comment by TobiasMorell** [comment]
From my understanding `Coroutiner` is not a type we have defined, and hence I'm guessing it's something that comes with either Arcadia or Clojure-clr. I know that there exists coroutines in Unity, so it could also be something there. However, we have not used coroutines in this small project.

My colleague has cloned the same project and is building it on Linux, where there are no problems.

**Comment by nasser** [comment]
`Coroutiner` does not come with either Arcadia or ClojureCLR. Maybe you meant [`Coroutine`](https://docs.unity3d.com/ScriptReference/Coroutine.html)? In any case, it does not look like it is used in your `unity.clj` file and you can safely remove it from your `:import` statement.

I am closing as this does not seem to be a bug in Arcadia or Clojure.
