### ISSUE TITLE
Roles added in editor mode disappear when exiting play mode on beta

### ISSUE THREAD

**Issue by Saikyun** [arcadia-unity/Arcadia#323]
Be me. Am on branch beta, commit ce84e89a4a95fe5480e4d63d5b56cb819affbcc1

Open an arcadia project. Open the file `<project path>/Assets/game/test.clj`. Add the following:
```cloure
(ns game.test
  (:require [arcadia.core :refer :all]))

(defrole dumb-role
  (update
   [obj k]
   (log "hej")))
```

Be in editing mode, open the repl. Write the following:
```clojure
user=> (load-file "Assets/game/test.clj")
;; #'game.test/dumb-role
user=> (in-ns 'game.test)
;; #object[Namespace 0xd44a0600 "game.test"]
game.test=> (role+ (object-named "Main Camera") :random/wat dumb-role)
;; #<Main Camera (UnityEngine.GameObject)>
```
So far, looking good.
![Yes](https://new.memset.se/5850/bUs3TWI0cnBha3J2eGc9PQ)
Then enter play mode. And everything is the same. A lot of "hej" appears in the chat.
Only Monika is missing.

Then exit play mode.

Sadness.
![Sadness](https://new.memset.se/5851/SStmZ2NRV1V0bDF3Smc9PQ)

If you follow the same steps on develop, commit dbfbd785b9e18ed9f83996b2608169991b4ada76
Then everything will work as expected.

**Comment by timsgardner** [comment]
Fixed as of e05ffe5866bcb27318f24cb97f7a089d475408fb
