### ISSUE TITLE
Can't disconnect and reconnect using Cider + Emacs without restarting Emacs

### ISSUE THREAD

**Issue by Saikyun** [arcadia-unity/Arcadia#325]
Steps to reproduce:
1. Start Emacs & Arcadias nREPL
2. Use `cider-connect` to connect to the nREPL
3. Evaluate `(+ 1 1)` in the repl, you'll get `2` back.
4. Kill the repl buffer and it's associated process.
5. Use `cider-connect` again.
6. Evaluate `(+ 1 1)` in the repl. Now you're stuck.
(7. THE FIX) Restart Emacs.

**Comment by nasser** [comment]
I'm reproducing this on Linux. Looking into it.

**Comment by nasser** [comment]
Fixed in cddd5fc
