### ISSUE TITLE
Importing Arcadia fails with "Type or namespace 'Util' does not exist"

### ISSUE THREAD

**Issue by Rovanion** [arcadia-unity/Arcadia#334]
Running Unity version 2018.3.0f2 Personal extracting both the source tarball of Arcadia 1.0.1 beta from GitHub and the master branch at a44bea75c128e704248617c057dc187549ab8954 into the Assets folder, with the name Arcadia, of two separate projects created from the Lightweight RP template. I also tried using the normal 3D template to no avail. I'm running on 64-bit Ubuntu 18.04.

All three times the same error has appeared:

```
Assets/Arcadia/Helpers/PlayerCallbacks.cs(29,5): error CS0234: The type or namespace name 'Util' does not exist in the namespace 'Arcadia' (are you missing an assembly reference?)
```

In Arcadia/Helpers/Util.cs though there is a public class Util in the namespace Arcadia, so :man_shrugging:.

**Comment by Rovanion** [comment]
Running 2017.4.17f1 Personal I got a different but probably related error message:

```
Assets/Arcadia/Helpers/Callbacks.cs(5,7): error CS0246: The type or namespace name `clojure' could not be found. Are you missing an assembly reference?
```

I would guess that the difference is in which order the different versions tries to load the files. The last error in the series of errors I get is about the same as before:

```
Assets/Arcadia/Helpers/PlayerCallbacks.cs(20,17): error CS0246: The type or namespace name `Var' could not be found. Are you missing an assembly reference?
```

**Comment by sogaiu** [comment]
Out of curiosity, have you seen the following?

https://github.com/arcadia-unity/Arcadia/wiki/Getting-Started#user-content-mono-runtime-configuration

**Comment by nasser** [comment]
No problem, this is a very common sticking point with people new to Arcadia. We would love to automate it or even throw a more meaningful error, but the changing nature of Unity (their API to check the Mono settings changes pretty drastically between versions) this is pretty hard to do in practice. If there's a better way we can document, please let us know!

**Comment by nasser** [comment]
Great, thanks! Much appreciated!
