### ISSUE TITLE
InvalidOperationException: Attempting to serialize unserializable hooks (Unity 2018.3)

### ISSUE THREAD

**Issue by hww** [arcadia-unity/Arcadia#341]
With Unity Editor, select (in hierarchy) created by script below "some object". It will produce error messages in log: **InvalidOperationException: Attempting to serialize unserializable hooks:**

```C#
(let [the-object (new UnityEngine.GameObject "some object")]
  (hook+
    the-object
    :update
    :log-name
    ;; `obj` will be the `the-object`, `role-key` will be `:log-name`
    (fn [obj role-key]
      (log (.name obj)))))
```

Full error message:
```
InvalidOperationException: Attempting to serialize unserializable hooks:
  Key: :log-name; Hook Function: game$core$create_gameobject_with_updatefn__37272__37276
ArcadiaBehaviour.UnityEngine.ISerializationCallbackReceiver.OnBeforeSerialize () (at Assets/Arcadia/Components/ArcadiaBehaviour.cs:226)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by sogaiu** [comment]
I was able to reproduce this with 33beafb and 488e64b on 2018.3.0f2 with Manjaro Linux.

Doing (use 'arcadia.core) first helped too ;)

**Comment by Saikyun** [comment]
I'm not sure that that's the issue, but you might want to read here: https://github.com/arcadia-unity/Arcadia/wiki/Using-Arcadia#why-use-vars-rather-than-functions
If nothing else it's "best practice" to use vars, so it's good to know either way. :)

**Comment by sogaiu** [comment]
As a side note, the code in question is from the Wiki -- or is based on it, see:

https://github.com/arcadia-unity/Arcadia/wiki/Using-Arcadia#hooks-and-state

So may be the examples should reflect the recommendation -- or at least mention the practice...

**Comment by nasser** [comment]
The behavior is expected, but this is a bug in our documentation. I've updated the examples in the wiki to reflect the preferred practice of using vars as hooks instead of anonymous functions. Thanks for catching this!
