### ISSUE TITLE
Need async api for handle Task.

### ISSUE THREAD

**Issue by netpyoung** [arcadia-unity/Arcadia#342]
I know there is core.async (not yet completed on clojureclr)
 anyway for compatibility with c# we need async api for c#(handle Task)
Coroutine itself is not useful.

**Comment by nasser** [comment]
I agree, a way to handle Tasks would be great. That's out of scope for this project, though, where the focus is on integrating Clojure into Unity, and more of an issue for [ClojureCLR](https://github.com/clojure/clojure-clr) itself. It could even be a standalone library.
