### ISSUE TITLE
NuGetAssetParser.exe quarantined by virus scanner on macos

### ISSUE THREAD

**Issue by pmonks** [arcadia-unity/Arcadia#356]
The file NuGetAssetParser.exe, bundled in the Arcadia releases, gets quarantined by [Avira AntiVirus](https://www.avira.com/en/free-antivirus-mac) on macos Mojave.  Note that Avira doesn't detect an actual virus - the file is flagged via heuristics:

![image](https://user-images.githubusercontent.com/54865/54692583-73f4d400-4ae2-11e9-8769-fa7efeaa4d64.png)

**Comment by pmonks** [comment]
Note: this is easy enough to remedy - Avira offers a "restore" option.  The issue is more the potential perception that the Arcadia release binary contains a virus.

**Comment by nasser** [comment]
Yikes, thanks for catching that! That's disconcerting. We don't use `NuGetAssetParser.exe` anymore so I will just pull it from the repo and cut a new release. But I wonder what's causing it to get flagged in the first place? We'd like the option of including `.exe` files in the future and don't want to wind up here again... Does the antivirus just not like `.exe` files or is there something about that file in particular that upset it?

**Comment by pmonks** [comment]
@nasser sadly I have no clue how Avira works in detail, and the fact that Avira is reporting a "heuristic" failure rather than reporting the detection of a specific virus makes it all the more murky...
