### ISSUE TITLE
Does it work at runtime? 

### ISSUE THREAD

**Issue by darkhog** [arcadia-unity/Arcadia#365]
I want to use Arcadia for runtime scripting capabilities for my game's modding facilities, but I need to know if it can compile/interpret at runtime (sans Unity Editor). I also need to know if there are facilities to add/remove functionalities to sandbox the environment and add stuff specific to my game.

**Comment by nasser** [comment]
Arcadia works great outside of the Unity editor on the following platforms:

* Desktop (Windows, Linux, macOS)
* Android

Other platforms are either known to not work or will likely have problems. More details and links are [on the wiki](https://github.com/arcadia-unity/Arcadia/wiki/Limitations).

Closing as this isn't an issue per se, but I am happy to keep talking on [the Gitter channel](https://gitter.im/arcadia-unity/Arcadia) if you'd like.
