### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#39]
Our compilation code assumes Unix paths. This seems to be the only obstacle to Windows support.

**Comment by selfsame** [comment]
Here's a diff on getting -b components sorted for windows

https://github.com/selfsame/Arcadia/commit/ae69a36fc69b68c4e86c3737ebe4203daf328cdc

(ignore the cljc edits, but I think the forceEditor stuff was an issue https://github.com/selfsame/Arcadia/commit/ae69a36fc69b68c4e86c3737ebe4203daf328cdc#diff-a42af4e91b410f60f60120e0970fa92cL16)

**Comment by timsgardner** [comment]
Is this still a thing? Not a hard fix...

**Comment by selfsame** [comment]
This was fixed a while ago and can be closed.
