### ISSUE TITLE
namespace for type wrangling

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#42]
Keep hitting some patterns and writing the same functions for type-hint macro machinery (eg ensure-type, type-symbol?, etc), should put them somewhere nice. Also need to determine good home for borderline macros like condcast (quite possibly core, given intensity of interop, but we should make a principled decision)

**Comment by nasser** [comment]
Everything relevant has been moved to `internal`, everything else has been pulled.
