### ISSUE TITLE
Wrapping policy

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#52]
Much better to have a small number of carefully-chosen features than lots of hasty ones, especially if we have all the functionality already anyway via interop. I'm nervous about the degree of wrapping we're doing. I don't think simply making all Unity methods first-class is worth the bloat to the public API,  certainly not without more solid type-hinting machinery. Wrapping also causes some weird side effects, like shadowing clojure.core (happens when we wrap Mathf). On the other hand it may well be useful to bulk zap Unity utility classes into collections of (type-hinted!) functions à la carte. Manipulating vector3's, for example, should probably be easier. My instinct is that we should manually target specific pieces of functionality that need some Clojure spiffing. Then, if it is possible to do non-jankily (which it may well not be), expose defwrapper as a public macro for users to selectively wrap Unity classes.

**Comment by nasser** [comment]
The policy in place is to wrap conservatively when a particular use case comes up over and over again (e.g. the former `linear` namespace). We've also done a lot of this already and folded it all into `arcadia.core`, so I am calling this closed.
