### ISSUE TITLE
condcast seems buggy

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#55]
got ``` System.InvalidCastException: Cannot cast from source type to destination type.``` when using with ```System.Text.RegularExpressions.Regex```. Might be optical illusion but worth writing some tests. Which we should be doing more of anyway.

**Comment by nasser** [comment]
`condcast->` was pulled from the project in 28a34adf0863ef4cbbe8be2e993a30dce879b9fc
