### ISSUE TITLE
File reorganization breaks paths

### ISSUE THREAD

**Issue by ikarth** [arcadia-unity/Arcadia#59]
A minor point that you may have already noticed, but renaming the project probably should also lead to renaming the paths (unless everything is still going in a /Clojure folder):

```
    static public string[] CompilationRoots = new [] {
        "Assets/Arcadia/Scripts",
        "Assets/Arcadia/Libraries",
        "Assets/Arcadia/Internal",
    };
```

**Comment by nasser** [comment]
New path structure is better reasoned and this bug no longer exists
