### ISSUE TITLE
defcomponent - missing some serializable types?

### ISSUE THREAD

**Issue by selfsame** [arcadia-unity/Arcadia#62]
Arcadia release seems to be missing String, GameObject, Transform (probably more)

```clj
  (import '[UnityEngine Vector3 Color GameObject])
  
  (arcadia.core/defcomponent Hinted [^String s ^int i ^float f ^GameObject go ^Transform t ^Vector3 v ^Color c] ) 

  (.AddComponent (find-name "Cube") Hinted)
```

results: ![types](https://cloud.githubusercontent.com/assets/2467644/4691771/38761842-5732-11e4-969a-3a4771ac9515.jpg)

**Comment by markfarrell** [comment]
Any updates on this?

**Comment by nasser** [comment]
It's back in again! Keeping an eye on it though.
