### ISSUE TITLE
Over-compilation/slow load times

### ISSUE THREAD

**Issue by chris-chambers** [arcadia-unity/Arcadia#63]
I ran into an interesting issue today that causes slow load times in the REPL and extraneous importing of .cjl.dll assets.  It appears to have come up before (see #21, a8e93f5801c71ad3d4ad5c74294b7e66ccb0a759, and 77f2f25dd153c9f50d54973763fdede0a5b41e92).

The reason for the slowdown, as #21 suggests, is that some .clj files from the Internal/clojure folder are recompiled, despite precompiled dlls being available.  It took a while to come up with a comprehensive explanation for why this happens, and in the end there was no nice, neat solution that I could see.  (Several moderately uncomfortable solutions exist.)

The problem is the result of an interaction between three things:
  - ClojureCLR's file search order
  - git's handling of timestamps
  - ClojureCLR's `*compile-path*` variable

#### Search Order

First, the file search order of the ClojureCLR runtime was a little surprising to me.  I expected the components of `CLOJURE_LOAD_PATH` to be searched in order, with maybe some fallback. See [RT.GetFindFilePathsRaw](https://github.com/arcadia-unity/clojure-clr/blob/master/Clojure/Clojure/Lib/RT.cs#L3453) for the whole story. The relevant except is:

  1. *a few we don't care about*
  1. `Path.GetDirectoryName(typeof(RT).Assembly.Location) => Internal`
  1. *one more we don't particularly care about*
  1. The contents of `CLOJURE_LOAD_PATH => [Compiled, Scripts, Libraries, Internal]`

So, Internal actually gets searched *before* Compiled because it contains `Clojure.dll`, which contains the `clojure.lang.RT` type.  This wouldn't be a problem, except for git's handling of timestamps.

#### Git Timestamps

Git does not preserve timestamps of files it tracks.  So, upon a fresh checkout of the Arcadia repository, the timestamps of the .clj.dll files in Internal may be older than the timestamps of the .clj files in Internal.  (On my machine, they always are, but I can't say for sure that git creates files breadth-first in all cases.)

Again, this wouldn't be a problem, except for ClojureCLR's handling of `*compile-path*` (with regard to search paths).

#### \*compile-path\*

ClojureCLR's `*compile-path*` variable can be set to any folder, but it is not explicitly included in the search order mentioned above.  So, it might come first (ideal), non-first (possibly bad) or not at all (certainly bad).

#### Final Effect

The total effect of these three properties allows the following:

Start conditions:
- `Internal/clojure.core.clj.dll` (git happens to create this slightly earlier, older timestamp)
- `Internal/clojure/core.clj` (git happens to create this slightly later, newer timestamp)

Steady State:
  1. Compile or load something that depends on `clojure.core`.
  1. `RT.load` finds `Internal/clojure.core.clj.dll`.  It is older than `Internal/clojure/core.clj`
  1. To bring things up to date, `Internal/clojure/core.clj` is compiled and placed into `*compile-path*` (in this case, Compiled/.  `Internal/clojure.core.clj.dll` is untouched.)
  1. Because of the search order, next time through the loop, the untouched `Internal/clojure.core.clj.dll` will still be found before the one that was just compiled, triggering another compilation (and so on).

#### Possible Solutions

  - Remove the precompiled .clj.dll files from Internal/.  This will cause a once-per-project performance hit the first time an Internal .clj is loaded, but there shouldn't be any issues thereafter.
  - Move the precompiled .clj.dll files to Compiled/.  Seems a little messy, but I don't see why it wouldn't work.  Because of git's timestamp handling, sometimes after a checkout, a recompile will occur, but only once per module.
  - Change ClojureCLR's search order to first consider `*compile-path*`, if it is set.  This is probably the tidiest solution, but I am not qualified to say whether the semantics are correct for all clojure programs.
  - Touch all the .clj.dll files sometime after git checkout.  a8e93f5801c71ad3d4ad5c74294b7e66ccb0a759 took this route, but there are downsides.  If a user intentionally modifies—or even accidentally updates the write time of—a .clj in Internal, they'll be back to the steady state above.  It's even possible that the code will be compiled but never actually loaded, because of the search order.  I haven't analyzed the ClojureCLR compilation and loading process fully enough to say for sure.
  - Moving `Clojure.dll` out of `Internal` would clean up the weird `Internal, Compiled, Scripts, Libraries, Internal` search order.  But again, in cases where git's timestamps happen to come out wrong, there will be a once-per-project compile for each module.

I'm not crazy about any of these solutions.  Hopefully there is a better one out there.

**Comment by nasser** [comment]
Most of these issues have been addressed, including patching the compiler to be smarter about load order, loading named typed, and file timestamps. If you see anything like this again, let us know!
