### ISSUE TITLE
core/replace-component

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#68]
There is no way to swap out a component attached to a gameobject. Idiomatic unity is to destroy the component, then add the new one. This is annoying in the REPL. `replace-component` would look something like

``` clj
(defn replace-component [^GameObject go ^Type ct]
  (if-let [c (get-component go ct)]
    (destroy c))
  (add-component go ct))
```

**Comment by timsgardner** [comment]
this is madness
