### ISSUE TITLE
Central location for support?

### ISSUE THREAD

**Issue by algoterranean** [arcadia-unity/Arcadia#97]
Is there a good central location for support and discussion on Arcadia other than filing issues? I have a number of questions to ask that don't belong here but I'm not sure where else to go. Maybe a google group or a thread on the unity forums would be appropriate? 

I'm thinking about things like:

What's the best way to translate existing component code (in, say, C#) to defcomponent? Particularly properties, private variables, and methods? 

I have some changes to the Arcadia code but I don't think they really fit in well with your coding style. How can we discuss these things? And has the license issue been resolved so we can issue pull requests?

And a few others. 

I just don't want to pollute this area with things that aren't actually issues. 

/edit P.S. The wiki could use some updating as well. I can do that this week, if you'd like. I'm in the middle of integrating Arcadia into a large Boo/C# unity project (both with Asset source files that are compiled by unity and externally compiled DLLs) so I'm tripping over a lot of little things that most probably aren't.

**Comment by acron0** [comment]
Which IRC server?

**Comment by nasser** [comment]
Freenode

**Comment by nasser** [comment]
https://gitter.im/arcadia-unity/Arcadia is the best place now for chatting
